### ISSUE TITLE
PyCharm

### ISSUE THREAD

**Issue by gauthiermartin** [rudrab/Shadow#100]
[Desktop Entry]
Version=1.0
Type=Application
Name=PyCharm
Icon=/opt/pycharm/bin/pycharm.png
Exec="/opt/pycharm/bin/pycharm.sh" %f
Comment=The Drive to Develop
Categories=Development;IDE;
Terminal=false
StartupWMClass=jetbrains-pycharm

**Comment by rudrab** [comment]
Hi,
Thanks a lot for your request. pycharm is pushed. 
Also, check [this](https://rudrab.github.io/Shadow/#icon-themed-but-does-not-appear), as pycharm is using absolute path.

Please don't forget to upvote it in gnome-look if you like the icon.
