### ISSUE TITLE
Icon Request :Cisco AnyConnect

### ISSUE THREAD

**Issue by gauthiermartin** [rudrab/Shadow#101]
It would be nice to have an icon for this 

[Desktop Entry]
Type=Application
Name=Cisco Anyconnect Secure Mobility Client
Comment=Connect to a private network using the Cisco Anyconnect Secure Mobility Client
Exec=/opt/cisco/anyconnect/bin/vpnui
Icon=/opt/cisco/anyconnect/pixmaps/vpnui48.png
Terminal=false
Encoding=UTF-8

**Comment by rudrab** [comment]
Hi, 
Thanks for your request. 
Is it possible for you to paste the icon `/opt/cisco/anyconnect/pixmaps/vpnui48.png` (or may be a bigger size if available), as I am still searching how the default icon looks like.

**Comment by rudrab** [comment]
Hi,
I have pushed an icon, based on whats available on net. Kindly let me know if this is the latest icon. 
NB: to apply the icon, use https://rudrab.github.io/Shadow/#icon-themed-but-does-not-appear
