### ISSUE TITLE
Icon Request: Typora and Abricotine

### ISSUE THREAD

**Issue by happydemic** [rudrab/Shadow#105]
Still loving your work. I tried to buy you a coffee [on PayPal](https://www.paypal.me/RudraBanerjee), but got 'Your friend has grabbed their PayPal.Me URL, but isn’t sharing it with the world just yet'.

Two requests, because I use both.

[**Typora**](https://typora.io): a minimalist single-pane Markdown editor.
[typora.desktop](https://github.com/rudrab/Shadow/files/1379675/typora.desktop.txt)
`Icon=typora`
![typora](https://user-images.githubusercontent.com/12738878/31501150-563d12ec-af61-11e7-83ce-05c0ed0b7fae.png)

[**Abricotine**](https://github.com/brrd/Abricotine): another single-pane Markdown editor
[Abricotine.desktop](https://github.com/rudrab/Shadow/files/1379672/Abricotine.desktop.txt)
`Icon=Abricotine`
![Abricotine](https://user-images.githubusercontent.com/12738878/31501813-2cba1698-af63-11e7-9151-7a2dcc61881f.png)

Thanks!

**Comment by rudrab** [comment]
Hi,
Thanks a lot for your request and offer me coffee. Unfortunately, I am stuck with a way that my paypal is not working. I will grab my coffee later. :)
The icons are ready and pushed to repo. Please try it and let me know.

**Comment by happydemic** [comment]
Gorgeous as ever!
Just one thing - Abricotine has a capital 'A' in the .desktop file. So it needs to be renamed.

**Comment by rudrab** [comment]
Done and thanks.

**Comment by rudrab** [comment]
Hi, shamelessly, but since you were interested, what about a cup of coffee?

**Comment by happydemic** [comment]
Sent where, @rudrab ?

**Comment by rudrab** [comment]
Hi, Thanks again for your interest. This is my paypal.me: paypal.me/banerjeerudra

**Comment by rudrab** [comment]
Thanks a lot for your coffee. (I guess you are Emma Reisz)

**Comment by happydemic** [comment]
Thanks for the thanks, but please edit out the name.

On 8 Nov 2017, 09:34 +0000, rudrab <notifications@github.com>, wrote:

Thanks a lot for your coffee. (I guess you are Emma Reisz)

**Comment by rudrab** [comment]
done, thanks
