### ISSUE TITLE
Online Account: Wrong google icon

### ISSUE THREAD

**Issue by terencode** [rudrab/Shadow#108]
![image](https://user-images.githubusercontent.com/12665563/31626033-7fd7495c-b2a8-11e7-9fb3-a3a6a11c321d.png)

It should be: 

![image](https://upload.wikimedia.org/wikipedia/commons/5/53/Google_%22G%22_Logo.svg)

instead of the google+ logo.

**Comment by rudrab** [comment]
Hi, Thanks for pointing this out. I will do that ASAP

**Comment by terencode** [comment]
Hey, not a life threatening issue so no need to rush ;)
