### ISSUE TITLE
SVG icon

### ISSUE THREAD

**Issue by jolkdarr** [rudrab/Shadow#11]
SVG files deserve their own icon.

One of the official logos should be used (http://www.w3.org/2009/08/svg-logos.html).

**Comment by rudrab** [comment]
svg has there own icon, in mimetypes, where it should be.
Using the logo is a good suggestion, but I am not sure how svg and w3c is related, or if the blooming flower is "official" logo of svg.
I will be very happy if you let me know.

**Comment by jolkdarr** [comment]
SVG technology is governed by the W3C like UML is ruled by the OMG.
All SVG logos are official and available under W3C Document License.

**Comment by rudrab** [comment]
Hi,
Thanks a lot for your comment.
I have modified and updated svg icon. Please pull it again

**Comment by rudrab** [comment]
I am closing this issue now...but feel free to reopen/comment

**Comment by jolkdarr** [comment]
Thanks for the update.

New icon is not applied unless I create a symbolic link in the mimetypes folder:
```sh
ln -s svg.svg image-svg+xml.svg
```
Note: I'm under `Ubuntu 14.04 LTS`.

**Comment by rudrab** [comment]
Ah...ok! Thanks for the update...I will update that in my repo too.
