### ISSUE TITLE
Icon request: Variety

### ISSUE THREAD

**Issue by jsnj** [rudrab/Shadow#111]
[Desktop Entry]
Name=Variety
Name[bg]=Variety
Name[de]=Variety
Name[es]=Variety
Name[fr]=Variety
Name[ja]=Variety
Name[ko]=버라이어티
Name[pl]=Variety
Name[ru]=Variety
Name[sr]=Разноврсност
Name[uk]=Variety
Comment=Variety Wallpaper Changer
Comment[bg]=Variety Wallpaper Changer
Comment[de]=Variety-Hintergrundbildwechsler
Comment[es]=Cambiador de fondos de pantalla Variety
Comment[fr]=Changeur de fonds d'écran Variety
Comment[ja]=Variety壁紙チェンジャー
Comment[ko]=버라이어티 배경화면 바꾸기 프로그램
Comment[pl]=Zmieniacz tapet Variety
Comment[ru]=Variety — программа для смены обоев
Comment[sr]=Измењивач позадина Разноврсност
Comment[uk]=Variety — проґрама для зміни шпалер
Comment[zh_CN]=Variety 壁纸切换器
Categories=GNOME;GTK;Utility;
Exec=variety %U
MimeType=text/uri-list;x-scheme-handler/variety;x-scheme-handler/vrty;
Icon=variety
Terminal=false
Type=Application
StartupNotify=false
Actions=Next;Previous;PauseResume;History;Preferences;
Keywords=Wallpaper;Changer;Change;Download;Downloader;Variety;

[Desktop Action Next]
Exec=variety --next
Name=Next
Name[bg]=Напред
Name[de]=Weiter
Name[es]=Siguiente
Name[fr]=Suivant
Name[ja]=次の壁紙
Name[ko]=다음
Name[pl]=Następna
Name[ru]=Следующее
Name[sr]=Следећа
Name[uk]=Наступні
Name[zh_CN]=下一个
OnlyShowIn=Unity;

[Desktop Action Previous]
Exec=variety --previous
Name=Previous
Name[bg]=Назад
Name[de]=Zurück
Name[es]=Anterior
Name[fr]=Précédent
Name[ja]=前の壁紙
Name[ko]=이전
Name[pl]=Poprzednia
Name[ru]=Предыдущее
Name[sr]=Претходна
Name[uk]=Попередні
Name[zh_CN]=上一个
OnlyShowIn=Unity;

[Desktop Action PauseResume]
Exec=variety --toggle-pause
Name=Pause / Resume
Name[bg]=Пауза / Подновяване
Name[de]=Pause / Weiter
Name[es]=Pausar/reanudar
Name[fr]=Pause / Reprendre
Name[ja]=一時停止/スタート
Name[ko]=일시 정지 / 재개
Name[pl]=Wstrzymaj / Kontynuuj
Name[ru]=Пауза / Продолжить
Name[sr]=Застани / Настави
Name[uk]=Призупинити / Продовжити
Name[zh_CN]=暂停 / 恢复
OnlyShowIn=Unity;

[Desktop Action History]
Exec=variety --history
Name=History
Name[bg]=История
Name[de]=Verlauf
Name[es]=Historial
Name[fr]=Historique
Name[ja]=履歴
Name[ko]=사용 기록
Name[pl]=Historia
Name[ru]=История
Name[sr]=Историјат
Name[uk]=Історія
Name[zh_CN]=历史
OnlyShowIn=Unity;

[Desktop Action Preferences]
Exec=variety --preferences
Name=Preferences
Name[bg]=Настройки
Name[de]=Einstellungen
Name[es]=Preferencias
Name[fr]=Préférences
Name[ja]=設定
Name[ko]=환경 설정
Name[pl]=Preferencje
Name[ru]=Параметры
Name[sr]=Поставке
Name[uk]=Налаштування
Name[zh_CN]=首选项
OnlyShowIn=Unity;

It's an svg located in /usr/share/icons/hicolor/scalable/apps. I've attached a png version.
![variety](https://user-images.githubusercontent.com/2219400/31958829-f83c9cf8-b8c0-11e7-9ff8-3e8a0c4568c2.png)

**Comment by tkleinhenz** [comment]
> [Desktop Entry]
> Name=Variety
> Name[bg]=Variety
> Name[de]=Variety
> Name[es]=Variety
> Name[fr]=Variety
> Name[ja]=Variety
> Name[ko]=버라이어티
> Name[pl]=Variety
> Name[ru]=Variety
> Name[sr]=Разноврсност
> Name[uk]=Variety
> Comment=Variety Wallpaper Changer
> Comment[bg]=Variety Wallpaper Changer
> Comment[de]=Variety-Hintergrundbildwechsler
> Comment[es]=Cambiador de fondos de pantalla Variety
> Comment[fr]=Changeur de fonds d'écran Variety
> Comment[ja]=Variety壁紙チェンジャー
> Comment[ko]=버라이어티 배경화면 바꾸기 프로그램
> Comment[pl]=Zmieniacz tapet Variety
> Comment[ru]=Variety — программа для смены обоев
> Comment[sr]=Измењивач позадина Разноврсност
> Comment[uk]=Variety — проґрама для зміни шпалер
> Comment[zh_CN]=Variety 壁纸切换器
> Categories=GNOME;GTK;Utility;
> Exec=variety %U
> MimeType=text/uri-list;x-scheme-handler/variety;x-scheme-handler/vrty;
> Icon=variety
> Terminal=false
> Type=Application
> StartupNotify=false
> Actions=Next;Previous;PauseResume;History;Preferences;
> Keywords=Wallpaper;Changer;Change;Download;Downloader;Variety;
> 
> [Desktop Action Next]
> Exec=variety --next
> Name=Next
> Name[bg]=Напред
> Name[de]=Weiter
> Name[es]=Siguiente
> Name[fr]=Suivant
> Name[ja]=次の壁紙
> Name[ko]=다음
> Name[pl]=Następna
> Name[ru]=Следующее
> Name[sr]=Следећа
> Name[uk]=Наступні
> Name[zh_CN]=下一个
> OnlyShowIn=Unity;
> 
> [Desktop Action Previous]
> Exec=variety --previous
> Name=Previous
> Name[bg]=Назад
> Name[de]=Zurück
> Name[es]=Anterior
> Name[fr]=Précédent
> Name[ja]=前の壁紙
> Name[ko]=이전
> Name[pl]=Poprzednia
> Name[ru]=Предыдущее
> Name[sr]=Претходна
> Name[uk]=Попередні
> Name[zh_CN]=上一个
> OnlyShowIn=Unity;
> 
> [Desktop Action PauseResume]
> Exec=variety --toggle-pause
> Name=Pause / Resume
> Name[bg]=Пауза / Подновяване
> Name[de]=Pause / Weiter
> Name[es]=Pausar/reanudar
> Name[fr]=Pause / Reprendre
> Name[ja]=一時停止/スタート
> Name[ko]=일시 정지 / 재개
> Name[pl]=Wstrzymaj / Kontynuuj
> Name[ru]=Пауза / Продолжить
> Name[sr]=Застани / Настави
> Name[uk]=Призупинити / Продовжити
> Name[zh_CN]=暂停 / 恢复
> OnlyShowIn=Unity;
> 
> [Desktop Action History]
> Exec=variety --history
> Name=History
> Name[bg]=История
> Name[de]=Verlauf
> Name[es]=Historial
> Name[fr]=Historique
> Name[ja]=履歴
> Name[ko]=사용 기록
> Name[pl]=Historia
> Name[ru]=История
> Name[sr]=Историјат
> Name[uk]=Історія
> Name[zh_CN]=历史
> OnlyShowIn=Unity;
> 
> [Desktop Action Preferences]
> Exec=variety --preferences
> Name=Preferences
> Name[bg]=Настройки
> Name[de]=Einstellungen
> Name[es]=Preferencias
> Name[fr]=Préférences
> Name[ja]=設定
> Name[ko]=환경 설정
> Name[pl]=Preferencje
> Name[ru]=Параметры
> Name[sr]=Поставке
> Name[uk]=Налаштування
> Name[zh_CN]=首选项
> OnlyShowIn=Unity;
> 
> It's an svg located in /usr/share/icons/hicolor/scalable/apps. I've attached a png version.
> ![variety](https://user-images.githubusercontent.com/2219400/31958829-f83c9cf8-b8c0-11e7-9ff8-3e8a0c4568c2.png)

PLEASE CALL ME JASON

**Comment by tkleinhenz** [comment]
jason please call me asap

**Comment by tkleinhenz** [comment]
JASON PLEASE CALL ME I NEED YOUR HELP

**Comment by rudrab** [comment]
i am totally confused....whats going on?

**Comment by tkleinhenz** [comment]
please contact jsnj  need to get a hold of him about a code issue
    On Wednesday, December 30, 2020, 10:58:03 PM EST, rudrab <notifications@github.com> wrote:  
 
 


i am totally confused....whats going on?

**Comment by rudrab** [comment]
who is jsnj? or its a wrong thread?

**Comment by tkleinhenz** [comment]
jsnj is ghost.  please ask him to contact me on this please

**Comment by tkleinhenz** [comment]
JAse Can you please email me asap

**Comment by tkleinhenz** [comment]
Jason can you call me asap
