### ISSUE TITLE
Icon Request: Master PDF Editor 4

### ISSUE THREAD

**Issue by jsnj** [rudrab/Shadow#114]
[Desktop Entry]
Name=Master PDF Editor 4
Comment=Edit PDF files
Exec=/opt/master-pdf-editor-4/masterpdfeditor4 %f
Path=/opt/master-pdf-editor-4
Terminal=false
Icon=/opt/master-pdf-editor-4/masterpdfeditor4.png
Type=Application
Categories=Office;Graphics;
MimeType=application/pdf;application/x-bzpdf;application/x-gzpdf;

![masterpdfeditor4](https://user-images.githubusercontent.com/2219400/31959972-47527a3a-b8c4-11e7-9912-625ccb268294.png)

**Comment by rudrab** [comment]
hi,
I have uploaded this, but you have to follow https://rudrab.github.io/Shadow/#icon-themed-but-does-not-appear
