### ISSUE TITLE
button minus shows x

### ISSUE THREAD

**Issue by RavanH** [rudrab/Shadow#116]
Open gnome tweak tool, switch to Shadow icons and then on the Font types tab (for example) there is the option to scale font size up or down. The down-scale button should be a minus sign but shows an X close button sign:
![screen print](https://user-images.githubusercontent.com/1184853/32410999-fe9f6162-c1cf-11e7-9286-46cc87068f4b.png)

**Comment by rudrab** [comment]
Hi, thanks a lot for pointing this out. I have updated it. Can you please pull it and check if this has broken anything else?

**Comment by RavanH** [comment]
seems to be ok :)

many thanks for this fantastic icon set!
