### ISSUE TITLE
Window full size / frame size button inconcistency

### ISSUE THREAD

**Issue by RavanH** [rudrab/Shadow#117]
HI again, I noticed a difference in the program button that is there to toggle between full size and windowed size program frames. When in windowed size, the button is coherent with the other two (close and hide) but in full size it seems to be the default one which does not match the other two. See screen prints:

![windowed](https://user-images.githubusercontent.com/1184853/32456125-c228b264-c324-11e7-9fc8-a82eb6615df9.png)

![full size](https://user-images.githubusercontent.com/1184853/32456134-caad217c-c324-11e7-8173-7684bd6ff782.png)

(simple terminal frame)

**Comment by RavanH** [comment]
Hmmm, it's because of the button bg color being an exact match of the the frame chrome color. When I choose the application theme Radiance, the buttons look like this:

![schermafdruk van 2017-11-06 22-17-56](https://user-images.githubusercontent.com/1184853/32464462-66247252-c340-11e7-88ad-b013220b4ac0.png)

The outer shadow shows there is still a circle, it's just the fill color that is not changed to the darker shade as the other two...

**Comment by rudrab** [comment]
Hi, 
Thanks for reporting this bug to me. 
The icons are updated (in it's rudimentary form. Those close/max/min buttons don't  look good. I need to plan how I can represent them better. But at least it matches the theme.)
