### ISSUE TITLE
Icon request for Medleytext

### ISSUE THREAD

**Issue by murpholinox** [rudrab/Shadow#119]
[here](https://medleytext.net/)

The problem is that it is an appimage...so I am not sure ....how to proceed.
Glad to help in any way I can.

**Comment by murpholinox** [comment]
Found the desktop file:
[Desktop Entry]
Name=MedleyText
Comment=Take programming notes with style
Exec="/home/murph/Descargas/medley-latest.AppImage" %U
Terminal=false
Type=Application
Icon=appimagekit-medleytext
X-AppImage-Version=0.9.8
X-AppImage-BuildId=21a213d0-aca9-11a7-1407-57e2f5889593
X-Desktop-File-Install-Version=0.23
X-AppImage-Comment=Generated by /tmp/.mount_MDQ4LY/AppRun
TryExec=/home/murph/Descargas/medley-latest.AppImage

**Comment by rudrab** [comment]
Hi, thanks for your request. Kindly pull from git again and check if this is working.
Please consider upvoting in gnome-desktop if you like the theme.

**Comment by murpholinox** [comment]
Thanks.
![captura de pantalla de 2017-12-22 19-33-12](https://user-images.githubusercontent.com/732802/34315943-3dfacca8-e74f-11e7-90ea-aede5330265d.png)
Upvoting....where?

**Comment by rudrab** [comment]
If you are happy, then consider upvoting here: https://www.opendesktop.org/p/1012532/
