### ISSUE TITLE
Please make an icon for wine

### ISSUE THREAD

**Issue by dayemsiddiqui** [rudrab/Shadow#12]

**Comment by rudrab** [comment]
Wine is already there. Unless your distro uses some other name, please try to update shadow.

**Comment by rudrab** [comment]
Hi,
I am interested to know if an update solved your problem.
If not, please give me following information, I will be happy to create the icon:
Info needed:
1) your distro  and version(not exactly required, but I am just curious)
2) Output of the command:
 `grep Icon /usr/share/applications/wine.desktop`

**Comment by dayemsiddiqui** [comment]
Thanks my problem was solved by rebooting! :)

**Comment by dayemsiddiqui** [comment]
you may close this issue
