### ISSUE TITLE
How to override the icon in the gnome dash?

### ISSUE THREAD

**Issue by murpholinox** [rudrab/Shadow#120]
I am sorry to bother ....again....but
Do you know how can I override the icons in the following pictures with the appropriate shadow icons?
![1](https://user-images.githubusercontent.com/732802/34317147-c59dd42a-e76d-11e7-8017-6a9096d27d0e.png)
![2](https://user-images.githubusercontent.com/732802/34317148-c77f85e0-e76d-11e7-9576-83c9136e61c4.png)
![captura de pantalla de 2017-12-22 23-18-59](https://user-images.githubusercontent.com/732802/34317185-a96bbe4c-e76e-11e7-865c-773aa1da6b88.png)

The problem arises with ...all third party software...mendeley, vesta, coot, mathematica, medleytext....
Thanks

**Comment by rudrab** [comment]
Hi,
Thanks for reporting this. But this is somewhat involved with those code itself. I faced similar issue with both mendeley and VESTA. While VESTA people does not response, for mendeley, its a known bug:
http://support.mendeley.com/customer/portal/questions/16348265-on-linux-mendeley-launcher-icon-and-running-application-icon-do-not-match

**Comment by murpholinox** [comment]
That's too bad. I thought it was a gnome (hidden somewhere) setting. So....not a lot we can do...right?

**Comment by rudrab** [comment]
I don't think we either as user or icon creator, can do much. For VESTA though, I use a workaround to replace (i assume you are using rpm) `/usr/local/vesta-3.4.0/img/logo.png` by the `~/.icon/Shadow/sclable/apps/vesta.svg`.

You can either use `convert` or `inkscape` to do the conversion.

**Comment by murpholinox** [comment]
workaround works.
Thanks

**Comment by rudrab** [comment]
I am closing this issue now. Please dont hesitate to open this/new issue if you face any problem in future.
Please consider upvoting this project at gnome-look: https://www.opendesktop.org/p/1012532/

**Comment by rudrab** [comment]
Hi, sorry to bother you again. I am not sure which version of fedora and mendeley you are using, but I have built a mendeley rpm for f27, which solves the problem. 
Are you interested? Kindly let me know, then I can put it somewhere for you to download

**Comment by murpholinox** [comment]
Yes. I'm using fedora 27. Thank you very much.

**Comment by rudrab** [comment]
Hi, 
Please install the mendeley desktop using [this](https://drive.google.com/file/d/1pQx1IidRdRjzhLgC4hP2kvz5GI00ItZN/view?usp=sharing) link.This works for my machines. But I will be really grateful if you kindly let me know if this is working. 

Kindly check the screenshot. this shows where to add vote. :)
![screenshot from 2018-01-05 21-33-15](https://user-images.githubusercontent.com/4639447/34647135-37ce9e2e-f3a0-11e7-9643-42fe6bc30e4a.png)

**Comment by rudrab** [comment]
please, can you let me know if mendeley is working?

**Comment by murpholinox** [comment]
Works perfect! 👍 
![screenshot from 2018-01-12 11-23-44](https://user-images.githubusercontent.com/732802/34887301-a389f638-f78b-11e7-8422-3c8d9e4e887e.png)
![screenshot from 2018-01-12 11-23-51](https://user-images.githubusercontent.com/732802/34887304-a4f58e88-f78b-11e7-96f7-ab77a361e6b6.png)

**Comment by murpholinox** [comment]
Thanks again!
