### ISSUE TITLE
Icon Request: TOR, Signal Desktop, & qTox

### ISSUE THREAD

**Issue by iwibassist** [rudrab/Shadow#122]
Love this icon pack, but was wondering if you could add icons for TOR Browser, Signal Desktop (the computer client for Signal Private Messenger), and qTox (Tox Client). Thank you and again I love the icon pack.

**Comment by rudrab** [comment]
Hi,
Thanks a lot for your icon suggestion. Can you kindly add the corresponding `.desktop` files?

**Comment by rudrab** [comment]
icons are done, waiting for your desktop file so that i can name those icons properly.
Best,

**Comment by iwibassist** [comment]
I deeply apologize, I am very young and just starting to learn Linux systems. Could you please, if possible, give me inscrutions as a step by step on how to do that? Again, I apologize.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by rudrab** [comment]
No problem. 
 `cd /usr/share/applications/` where you will find lot of `<name>.desktop` files. From those <name>, you can probably see which files you are looking for. 

If you cant figure it by name, check the name of your application in your dashboard, e.g., see I gave `Tor Browser in my dashboard. So, to find out the actual file, I will do:
![screenshot from 2018-01-21 11-34-03](https://user-images.githubusercontent.com/4639447/35191414-f215b25e-fe9f-11e7-910a-85338d9d8eb9.png)

```
$cd /usr/share/applications/
$grep "Tor Browser" *.desktop
torbrowser.desktop:Name=Tor Browser
torbrowser.desktop:Comment=Launch Tor Browser
torbrowser.desktop:StartupWMClass=Tor Browser
torbrowser-settings.desktop:Name=Tor Browser Launcher Settings
torbrowser-settings.desktop:Name[fr]=Tor Browser Launcher configurations
torbrowser-settings.desktop:Name[nl]=Tor Browser Launcher Instellingen
torbrowser-settings.desktop:Name[ru]=Tor Browser (настройки запуска)
torbrowser-settings.desktop:GenericName=Tor Browser Launcher Settings
torbrowser-settings.desktop:Comment=Tor Browser Launcher Settings
torbrowser-settings.desktop:Comment[fr]=Tor Browser Launcher configurations
torbrowser-settings.desktop:Comment[nl]=Tor Browser Launcher Instellingen
```

So, I am looking for these two file: `torbrowser.desktop` and `torbrowser-settings.desktop`

Hope, this helps

**Comment by iwibassist** [comment]
It says "No such file or directory"

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by rudrab** [comment]
You are getting `No such file or directory` while you are doing : `cd /usr/share/applications/` ? This is impossible....this is one of the inherent file in linux. Which distro(ubuntu/mint etc)
 you are using?

**Comment by iwibassist** [comment]
Ubuntu 17.10

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by rudrab** [comment]
from your terminal, copy paste that line, including the slash as well

**Comment by iwibassist** [comment]
Ok

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by rudrab** [comment]
or, open the files, click "Other Locations"->"Computer"->"usr"->"share"->"applications"

**Comment by iwibassist** [comment]
cd/usr/share/applications/
bash: cd/usr/share/applications/: No such file or directory

Sent with [ProtonMail](https://protonmail.com) Secure Email.

-------- Original Message --------

**Comment by rudrab** [comment]
ah..here you go:
`cd<space> /usr/share/applications/`

**Comment by iwibassist** [comment]
ok, and how do I find the tor.desktop after I put that commadn in?

Sent with [ProtonMail](https://protonmail.com) Secure Email.

-------- Original Message --------

**Comment by rudrab** [comment]
now, do `grep<space> Tor <space>*.desktop`
Sorry for the late reply.

**Comment by rudrab** [comment]
have you find the dirs?

**Comment by iwibassist** [comment]
I can't figure it out, my apologies. Thank for helping though.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by rudrab** [comment]
Hi,
I have added those three files, please download it from git and check if this works.
Kindly let me know.

**Comment by iwibassist** [comment]
This will sound very stupid, I know, but how do I download and install something from Github?

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by rudrab** [comment]
First and foremost, there is nothing called stupid question. 
Let me show you how to do it step by step. 
In terminal, write/copy these, remember the space:
```
cd .icons
ls   
```
If you see Shadow or shadow directory already exists, do `rm -rf Shadow` or `rm -rf shadow`. 
next,

```
git clone https://github.com/rudrab/Shadow.git
gsettings set org.gnome.desktop.interface icon-theme "Shadow"
```

This will make your Shadow theme activated.

**Comment by iwibassist** [comment]
Thank you so much

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by rudrab** [comment]
is it working now? including these 3 icons?

**Comment by iwibassist** [comment]
I apologize, could you resend the commands?

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by rudrab** [comment]
```
cd .icons
ls   
git clone https://github.com/rudrab/Shadow.git
gsettings set org.gnome.desktop.interface icon-theme "Shadow"

```

**Comment by iwibassist** [comment]
It says no filr or directory

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by rudrab** [comment]
Ok... Do step by step:
mkdir -p ~/.icons

**Comment by rudrab** [comment]
Then do the last two lines:
git... 
getting...

**Comment by rudrab** [comment]
After mkdir line, do
cd ~/.icons

**Comment by iwibassist** [comment]
Ok done, now what should I do?

Sent with [ProtonMail](https://protonmail.com) Secure Email.

-------- Original Message --------

**Comment by rudrab** [comment]
cd ~/.icons

**Comment by iwibassist** [comment]
What is clised 122?

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by rudrab** [comment]
???
What's that?

**Comment by iwibassist** [comment]
Came in the second to last email. So now thst sll those are done what should I do?

Sent with [ProtonMail](https://protonmail.com) Secure Email.

-------- Original Message --------

**Comment by rudrab** [comment]
Ok.... I don't think we are heading anywhere.
Its also too late here...gonna go to bed. Please check http://rudrab.github.io/Shadow/#installation tomorrow. I will update that in detail.

**Comment by rudrab** [comment]
hi,
Please check the link http://rudrab.github.io/Shadow/#installation. Its updated.
