### ISSUE TITLE
New Icon Request

### ISSUE THREAD

**Issue by banchaa** [rudrab/Shadow#124]
Please design icons for those applications:

Keepass2
Multisystem
Xpad
Bitcoin-qt

**Comment by rudrab** [comment]
hi,
Thanks for your request. If you are in any gtk-based system, kindly download and run the missingicon.py (https://www.opendesktop.org/p/1210642/) and send me the files (So that I know how the default icons look like.)
Thnaks.

**Comment by banchaa** [comment]
Hi,
Thanks for that fast respond. Icons are compressed and attached in this post.

[iconrequest.tar.gz](https://github.com/rudrab/Shadow/files/1711928/iconrequest.tar.gz)

**Comment by rudrab** [comment]
Hi,
few of your request icons are updated. Kindly have a look. If you like the icon theme, don't forget to upvote it at https://www.opendesktop.org/p/1012532/ and https://www.opendesktop.org/p/1210642/
