### ISSUE TITLE
Icon Request: Retroarch

### ISSUE THREAD

**Issue by Alfedi** [rudrab/Shadow#125]
It would be great to get a personalize icon for the emulator that Retroarch is. Thank you for your attention

**Comment by rudrab** [comment]
Hi, 
kindly run  https://www.opendesktop.org/p/1210642/ script so that I can see the default icon and icon name. Alternatively, you can find and send me the icon manually.

**Comment by rudrab** [comment]
Hi, many of your icons are added. Please have a look. 
If you like the icons, please consider upvote it at https://www.opendesktop.org/p/1012532/ and https://www.opendesktop.org/p/1210642
