### ISSUE TITLE
Icon request: Tusk

### ISSUE THREAD

**Issue by happydemic** [rudrab/Shadow#127]
Hi there, still enjoying your icons.

You have a [very pretty icon](https://github.com/rudrab/Shadow/blob/master/scalable/apps/whatever.svg) for the Evernote client Whatever - so pretty that it helped me to settle on Whatever as my Evernote client of choice! But Tusk is being more [actively developed](https://www.omgubuntu.co.uk/2018/02/tusk-evernote-client-snap-app) at the moment and has some great features, so I've made the switch. If you have time, I'd love a Tusk icon.

[**Tusk**](https://github.com/klauscfhq/tusk): a "refined Evernote desktop app"
tusk-app.desktop
`Icon=tusk-app`
![tusk-app](https://user-images.githubusercontent.com/12738878/36588272-817cfcba-187f-11e8-9bf1-7342ec9c0166.png)

**Comment by rudrab** [comment]
thanks for your request. Tusk is pushed.Please check.
