### ISSUE TITLE
Icon not working for KDE

### ISSUE THREAD

**Issue by kevinsmia1939** [rudrab/Shadow#129]
I put your icon theme in /usr/share/icons but I don't see icon in the settingat all
Manjaro KDE stable

**Comment by rudrab** [comment]
hi, sorry for the delayed reply, have you put the icons inside shadow direcrory, and run the changecolor.py to choose KDE? 
Alternatively, just rename `index.theme_kde` to `index.theme`.

**Comment by kevinsmia1939** [comment]
I did not find a file called index.theme_kde but index.theme
So I rename index.theme to index.theme_kde instead. Still not showing icon theme to choose.
I run chanecolor.py and still same problem.
https://imgur.com/66Wm60S

**Comment by kevinsmia1939** [comment]
I run changecolor.py in /usr/share/icons/Shadow

**Comment by rudrab** [comment]
Have you extracted the tar file in /usr/share/icons?  
I have checked the directory, and it should work.

**Comment by rudrab** [comment]
Hi,  the git file is not for KDE users. Those are for gtk based users only. Please go to https://www.opendesktop.org/p/1012532/ and there you will find the dedicated theme for KDE user (the same theme, but since KDE doesn't support transparency, svg's are converted to png).

**Comment by kevinsmia1939** [comment]
Thanks it work now

**Comment by rudrab** [comment]
Thanks a lot for letting me know. Please also let me know if you have any icon missing (I guess many system icons will be missing, as I dont use KDE myself). 
Also, please consider upvoting it at opendesktop site.
Best,
