### ISSUE TITLE
"Icon request"

### ISSUE THREAD

**Issue by cet1** [rudrab/Shadow#13]
Can you please make an icon for Zim Desktop Wiki.Thank you for all the hard work.

**Comment by rudrab** [comment]
Hi,
I am very sorry for the delay. I missed the mail.
But now this in updated and included in the repo.
Kindly pull the git once again.

**Comment by rudrab** [comment]
I am closing the issue now, but feel free to reopen if you have any problem.
Sorry for the delay again.

**Comment by cet1** [comment]
Thank you very much
