### ISSUE TITLE
Icon Request: MATLAB

### ISSUE THREAD

**Issue by jomobro** [rudrab/Shadow#130]
It would be great to have a MATLAB (developed by Mathworks) icon. Currently it's the only one on my favourites bar without your excellent theme. Unfortunately, MATLAB isn't installed via a package manager so the missingicon.py script doesn't find the icon. However, an image search of 'matlab icon' shows the correct one. Cheers!

**Comment by rudrab** [comment]
Hi,
thanks for your request. MATLAB is actually themed, but the problem is MATLAB doesn't provide the .desktop file for generic icon theme. You need to copy the matlab.desktop file to `~/.local/share/applications` and edit the line `icon=/some/full/path/matlab` to `icon=matlab`. 

This will work.

**Comment by rudrab** [comment]
hi, can you plz confirm if it is solved?

**Comment by jomobro** [comment]
Hi, my computer is currently being repaired, I’ll test it out once I get it back


Sent from Yahoo Mail for iPhone


On Tuesday, June 19, 2018, 8:01 am, rudrab <notifications@github.com> wrote:


hi, can you plz confirm if it is solved?

**Comment by jomobro** [comment]
Hello,
Sorry for the very long delay. Where can I find the matlab.desktop file?

**Comment by rudrab** [comment]
Hi,
That's hard to tell, as it will depend on your installation.  You can check:
```
cd /
find . -name matlab.desktop
```
 or manually check `/usr/local/applications` or `/usr/share/applications `

But, if this is already in your path,  you may try to put this in your `~.local/share/applications/`:
```
Version=1.0
Type=Application
Terminal=false
Exec=matlab
Name=Matlab
Icon=matlab
Categories=Development

```
