### ISSUE TITLE
Icon request: Freeplane, Birdfont

### ISSUE THREAD

**Issue by luforst** [rudrab/Shadow#132]
### freeplane.desktop
[Desktop Entry]
Name=Freeplane
Exec=/usr/bin/freeplane %F
Icon=freeplane

![freeplane](https://user-images.githubusercontent.com/20029498/43685734-a7bb1592-98b8-11e8-8938-80b4bcb5d27b.png)

### birdfont.desktop
[Desktop Entry]
Name=Birdfont
Name[ru]=Birdfont
Comment=Font editor
Comment[ru]=Редактор шрифтов
Exec=birdfont %U
Icon=birdfont

![birdfont_window_icon](https://user-images.githubusercontent.com/20029498/43685729-94c60988-98b8-11e8-9536-2b8b566dc620.png)

**Comment by rudrab** [comment]
Updated. Please check.
