### ISSUE TITLE
Icon's Missing and Icon's Request :)

### ISSUE THREAD

**Issue by vladik2738** [rudrab/Shadow#133]
Hello, today i've installed your icon pack, and everything seems good, but some icons didn't installed properly.

These programs are: Android Studio, GNOME Calculator,Spotify, GitKraken, Backups, Characters, Logs.
The interesting thing is there are no such `.desktop` files in my `/usr/share/applications` folder, so I think it just cant access icon paths. Maybe system stores them somewhere else (i think you might know where). 

Also I've found out that there are no icons for programs such as: Putty (program to access terminal via SSH), UKUU (ubuntu kernel update utility), and Sensor monitor (by default has the same icon as System Monitor, but now it doesn't) and GNU Paint.

Thank's for such a big job you have done.

**Comment by vladik2738** [comment]
I did some research, and fount out that missing files are in `/var/lib/snapd/desktop/applications` directory. I think something bad happened when i updated kernel and fixed snapd bug.

**Comment by rudrab** [comment]
Dear vladik2738,
Thanks a lot to report this problem. I have completely overlooked the snap/flatpack problem.
As for the case, Gnome calculator should be trivially available (if you use apt/dnf/yum). Also, Android Studio, GitKraken, Spotify etc are also themed. But I have no clue where you have installed them.  

Say, if you have installed say, Android Studio (AS) manually, so take the path of AS executable and follow the instructions here: 
http://rudrab.github.io/Shadow/#icon-themed-but-does-not-appear

Kindly let me know if that solves your problem.

**Comment by vladik2738** [comment]
Yes, I actually managed this problem by editing paths to icons already. I've installed these programs from official repo, but for some reasons their's desktop files were moved to `/var/lib/snapd/desktop/applications` :) However, thanks for an answer.
Could you please create icons for Putty (program to access terminal via SSH), UKUU (ubuntu kernel update utility), and Sensor monitor (by default has the same icon as System Monitor, but now it doesn't)? I haven't found them in your icon-pack, so i think they don't exist.

Thank you.

**Comment by rudrab** [comment]
vladik2738,
Thanks a lot for your reply and new icons request. Can you please provide me the corresponding desktop files (or just the icon name) and if possible, the icons as well?

**Comment by rudrab** [comment]
putty and ukuu added to git, kindly check and let me know if that us working for you.

**Comment by rudrab** [comment]
Thanks a lot for your reply.
If you like the icon set, please consider upvoting this in [opendesktop](https://www.opendesktop.org/p/1012532/https://www.opendesktop.org/p/1012532/)
