### ISSUE TITLE
Icon Request: Standard Notes

### ISSUE THREAD

**Issue by jameskerti** [rudrab/Shadow#137]
First, here is their logo.

<img width="41" alt="icon" src="https://user-images.githubusercontent.com/10284482/49687264-8314c080-fab5-11e8-8fbb-937b61f06138.png">

Then, here is the default icon they use on Linux now.

![](https://raw.githubusercontent.com/standardnotes/desktop/master/app/icon/Icon-512x512.png)

I've noticed that other custom icon themes have adapted the first image (the logo) rather than the second (the default icon that comes with the AppImage).

Here's the .desktop file I have.

Note that depending on the packaging, the icon path might be either **standardnotes** or **standard-notes** — so you might want to duplicate the icon with both names. (That's what I've seen other custom icon themes do.)

[Desktop Entry]
Name=Standard Notes
Comment=A standard notes app with an un-standard focus on longevity, portability, and privacy.
Exec=standardnotes-desktop
Terminal=false
Type=Application
Icon=standard-notes
StartupWMClass=Standard Notes

Thanks!

**Comment by rudrab** [comment]
hi...sorry for the extraordinary delay. The icon has been created and will be pushed in the next update. If you are still using shadow, kindly keep a look. Also, you may want to try my newer iconset
, [dual](https://rudrab.github.io/dual/)
