### ISSUE TITLE
Icon Request: unity-editor, unity-hub

### ISSUE THREAD

**Issue by AlePalu** [rudrab/Shadow#139]
Hi, this is absolutely my favorite icon theme ever! And great work for the mantainance!
Here another icon to be themed: unity-editor

I leave the original icon:
![unity](https://user-images.githubusercontent.com/9201005/61173208-81056980-a590-11e9-8211-41f841e9f8ca.png)

and the .desktop file:

```
[Desktop Entry]
Version=2019.1.7f1
Name=Unity
Exec=/usr/bin/unity-editor
Icon=unity-editor-icon
Terminal=false
Type=Application
StartupNotify=true
Categories=Development;IDE;Application;
MimeType=x-scheme-handler/com.unity3d.kharma; 
```

There is also another icon, unity-hub, equal to the unity-editor one above, so I think is enought to create a new .desktop file:

```
[Desktop Entry]
Name=Unity Hub
Comment=The Official Unity Hub
Exec=unityhub
Terminal=false
Type=Application
Icon=/usr/share/icons/Shadow/unity-editor.png
Version=2.0.1
MimeType=x-scheme-handler/unityhub;
Categories=Development;
```

Thank you!!

**Comment by rudrab** [comment]
Hi,
`unity-editor-icon` is added. But, as you can see, for unityhub, you have to modify the `.desktop` file as described at https://rudrab.github.io/Shadow/#icon-themed-but-does-not-appear

**Comment by AlePalu** [comment]
Great!
Just one thing, I've noticed .desktop file I've uploaded about unity-hub is not the original one (that was one I've modified by myself). Here the correct one:

```
[Desktop Entry]
Name=Unity Hub
Comment=The Official Unity Hub
Exec=unityhub
Terminal=false
Type=Application
Icon=unityhub
Version=2.0.3
MimeType=x-scheme-handler/unityhub;
Categories=Development;
```

In this way you should be able to theme also unity-hub in Shadow. Sorry for the inconvinient.

Thank you again!! And great work, the icon is awesome!!

**Comment by rudrab** [comment]
Yes, in this case, unityhub will be themed.
