### ISSUE TITLE
Icon Requests: Corebird, Opera, N1

### ISSUE THREAD

**Issue by d0od88** [rudrab/Shadow#14]
An icon for the GNOME desktop Twitter app Corebird, and the Nylas N1 e-mail client would be grand :)

**Comment by rudrab** [comment]
Hi, thanks for your request.
But I dont have any idea about Nylas N1. Can you give me the icon name and icon itself?
possibly you will find them in /usr/share/applications/N1.desktop

(NB: Corebird is ready. Just waiting to push them together)

**Comment by rudrab** [comment]
Both the icon is done. Kindly pull again.
I am closing the issue now. Please feel free to reopen and comment.
