### ISSUE TITLE
visual studio code shadow icon not shown

### ISSUE THREAD

**Issue by robin956** [rudrab/Shadow#146]
Hi,
first of all: Great work with the icons!

But my Visual Studio Code icon looks like default icon. Should it look like this? Because I know there is an shadow icon for VS Code you mentioned in another closed issue.

This is how it looks on my PC:
![visualstudiocode](https://user-images.githubusercontent.com/71229098/118357614-55cc7680-b57b-11eb-8cf4-3e5e03e3eec1.png)

Thank you!

**Comment by rudrab** [comment]
Hi, thanks for reporting this. however visualstudio is already installed. Can you send me your `.desktop` file? I guess the name has changed.

**Comment by rudrab** [comment]
Hello, one more thing. How have you installed id using deb/rpm/snap? I just checked by installing rpm and its working fine. So, kindly send me the .desktop file so that I get the name. 
![Screenshot from 2021-05-15 20-43-51](https://user-images.githubusercontent.com/4639447/118367571-b29d5080-b5be-11eb-93d8-80ef603eb7d7.png)

**Comment by robin956** [comment]
I installed it using snap. This is whats inside the .desktop file:

[Desktop Entry]
Name=Visual Studio Code
Comment=Code Editing. Redefined.
GenericName=Text Editor
Exec=code --force-user-env --no-sandbox --unity-launch %F
Icon=${SNAP}/meta/gui/com.visualstudio.code.png
Type=Application
StartupNotify=false
StartupWMClass=Code
Categories=Utility;TextEditor;Development;IDE;
MimeType=text/plain;inode/directory;application/x-code-workspace;
Actions=new-empty-window;
Keywords=vscode;

[Desktop Action new-empty-window]
Name=New Empty Window
Exec=code --force-user-env --no-sandbox --new-window %F
Icon=${SNAP}/meta/gui/com.visualstudio.code.png

**Comment by rudrab** [comment]
Hmm...the usual culprit. As you can see, the icon's path is hard coded. So, this doesn't take the icon from icon theme. Though I cont have experience with snap, can you put this on `~/.local/share/applications`:
```
[Desktop Entry]
Name=Visual Studio Code
Comment=Code Editing. Redefined.
GenericName=Text Editor
Exec=code --force-user-env --no-sandbox --unity-launch %F
Icon=com.visualstudio.code
Type=Application
StartupNotify=false
StartupWMClass=Code
Categories=Utility;TextEditor;Development;IDE;
MimeType=text/plain;inode/directory;application/x-code-workspace;
Actions=new-empty-window;
Keywords=vscode;

[Desktop Action new-empty-window]
Name=New Empty Window
Exec=code --force-user-env --no-sandbox --new-window %F
Icon=com.visualstudio.code
```

**Comment by robin956** [comment]
I placed this at the given location in a file called code.desktop but didn't change anything. Thinking about deleting VS code and then install it through other source.

**Comment by rudrab** [comment]
have you tried logout and login?

**Comment by robin956** [comment]
yes i tried. no change.

**Comment by rudrab** [comment]
Hmm....No Idea how snap reads the desktop files. So, I guess deb is the best option for the moment now.

**Comment by robin956** [comment]
I uninstalled VS code via snap now and then installed via deb. Still not working. Restarted PC etc.
Here is the new .desktop file created by deb installation:

[Desktop Entry]
Name=Visual Studio Code
Comment=Code Editing. Redefined.
GenericName=Text Editor
Exec=/usr/share/code/code --no-sandbox --unity-launch %F
Icon=com.visualstudio.code
Type=Application
StartupNotify=false
StartupWMClass=Code
Categories=Utility;TextEditor;Development;IDE;
MimeType=text/plain;inode/directory;application/x-code-workspace;
Actions=new-empty-window;
Keywords=vscode;

X-Desktop-File-Install-Version=0.26

[Desktop Action new-empty-window]
Name=New Empty Window
Exec=/usr/share/code/code --no-sandbox --new-window %F
Icon=com.visualstudio.code

Is there something wrong?

**Comment by rudrab** [comment]
Hi, this is strange. However, I have readded visualstudio in git (not in gnome-look). If you are using git, can you pull?

**Comment by robin956** [comment]
I switched from gnome-look to git now and it works! Thank you so much!

**Comment by rudrab** [comment]
Its great to know that its helping. Somehow the file got corrupted (may be)! The gnome-look will be updated soon. 
Also, may I request you to try my other icon "Dual"? 
Please, dont forget to upvote the icon in gnome-look.

**Comment by robin956** [comment]
Should it also have VS Code as icon?

**Comment by robin956** [comment]
Dual also looks amazing but the VS Code Icon in there is the same as in Shadow.

**Comment by rudrab** [comment]
Thanks for letting me know again.
visualstudio icon in dual is now updated in git. It will be updated in gnomelook within few days.
