### ISSUE TITLE
missing weather icon

### ISSUE THREAD

**Issue by maxnumberone** [rudrab/Shadow#16]
Hello,

I dont' know if it's related to my theme or to the extension (https://extensions.gnome.org/extension/750/openweather/) but it seems like at least one icon is missing from the weather icons : 

https://www.dropbox.com/s/d461t88mpurg55f/missing%20weather%20icon.png?dl=0

I think the icon you could see at the left of the screenshot is this one : /usr/share/icons/Adwaita/scalable/status/weather-few-clouds-symbolic.svg
I've found the same for the night so maybe it's also missing : /usr/share/icons/Adwaita/scalable/status/weather-few-clouds-night-symbolic.svg

thanks,
Regards

**Comment by rudrab** [comment]
Hi, 
You are right that few icons are missing from weather icons. I will update them as soon as possible.
To confirm, I also use openweather and it has nothing to do with that.

**Comment by rudrab** [comment]
the weathe icons are uploaded. You can pull it right now, or wait for #17 .

**Comment by maxnumberone** [comment]
Sorry, Forgot to answer, weather icons are good now,
Thanks.
