### ISSUE TITLE
new icons

### ISSUE THREAD

**Issue by maxnumberone** [rudrab/Shadow#17]
Hello again ;)
Could it be possible to add icons for the following applications ?
Veracrypt (icon name : veracrypt) : Disk encryption with strong security based on TrueCrypt
Filebot (icon name : filebot) : tool to rename TV/anime shows, download subtitles, and validate checksums
Pdfmod (icon name : pdfmod) : Simple application for modifying PDF
Thanks,
Regards

**Comment by rudrab** [comment]
icons updated. Please pull it.
I am closing this issue, but feel free to reopen and comment
