### ISSUE TITLE
New icons

### ISSUE THREAD

**Issue by Minda1975** [rudrab/Shadow#18]
[Icon request] 
#Hello. Thank you for your hard work. I have one request. Please, can you add a new icons for Pale Moon (web browser)  and DeadBeef (audio player)? Thank you.

**Comment by rudrab** [comment]
Hi, 
Thanks for your request. 
Its added to my to-do list. 
Will be updated soon.

**Comment by Minda1975** [comment]
Thank you, rudrab.

**Comment by rudrab** [comment]
Hi,
Sorry for the delay., but the icons are updated now. Kindly pull it.

**Comment by Minda1975** [comment]
Thank you, rudrab. Pulling it.
