### ISSUE TITLE
Icon request

### ISSUE THREAD

**Issue by gkroon** [rudrab/Shadow#2]
This is great flat icon set, thanks for this. Would you be willing to also create icons for the following missing packages?
Iceweasel
Icedove
Kodi
GParted
Redshift
Steam
Synaptic
MPV player
PlayOnLinux

Thanks again!

**Comment by rudrab** [comment]
Hi gkroon,
Thanks for your request.
I have added the icons. Please update using git.
It will be great if you kindly  up-vote the theme in gnome-look.
I am closing the issue, but feel free to reopen and comment.
