### ISSUE TITLE
wrong network icon [visible when closing transmission]

### ISSUE THREAD

**Issue by zoutiyx** [rudrab/Shadow#20]
The network icon has not been updated in shadow, it is still the default and can be seen when closing transmission.

_![closing transmission](http://s8.postimg.org/79t8dlu5x/transmission.png)_

**Comment by rudrab** [comment]
Hi, 
Thanks for reporting this `bug`.  New icons are updated. Please pull it.
I am now closing this issue, but feel free to reopen and comment if this doesn't solve your problem.
