### ISSUE TITLE
Missing playonlinux Icon

### ISSUE THREAD

**Issue by zoutiyx** [rudrab/Shadow#21]
Title says it all, the playonlinux icon needs updating

**Comment by rudrab** [comment]
Hi, 
Playonlinux is already in the repo. Can you post here your /usr/share/applications/playonlinux.desktop file so that I can check if your distro is using some different name?

**Comment by zoutiyx** [comment]
Okay. I fixed it. it uses 

> Icon=/usr/share/playonlinux/etc/playonlinux.png


changed it to playonlinx and I see it now. Thanks.

**Comment by rudrab** [comment]
Thanks, closed
