### ISSUE TITLE
preferences-system-windows icon for mate-tweak tool

### ISSUE THREAD

**Issue by dan-not-the-man** [rudrab/Shadow#22]
`File /usr/bin/mate-tweak, line 815, in <module>`
`MateTweak()`
`File /usr/bin/mate-tweak, line 669, in __init__`
`img=theme.load_icon(sidePage.icon, 36, 0)`
`mate-tweak crashed with GLib.Error in __init__():gtk-icon-theme-error-quark: Icon 'preferences-system-windows' not present in theme Shadow-master (0)`

From the crash report when trying to launch mate-tweak in Ubuntu MATE 15.10 x64. Thanks.

**Comment by rudrab** [comment]
Hi, Thanks for reporting this error. The icon is added. Kindly pull this again.
I am now closing this issue...kindly reopen it if you find any problem

**Comment by dan-not-the-man** [comment]
Haha, mate-tweak launched instantly. Thanks again!

On Thu, Mar 10, 2016 at 4:46 AM, rudrab <notifications@github.com> wrote:

> Hi, Thanks for reporting this error. The icon is added. Kindly pull this
> again.
> I am now closing this issue...kindly reopen it if you find any problem
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rudrab/Shadow/issues/22#issuecomment-194759203>.
>



-- 
Dan Chambers
Mobile: 404-519-2745
Skype: dchambers76

**Comment by rudrab** [comment]
Hi Dan,
Thanks for your Cofee...It was awesome
