### ISSUE TITLE
1.6 release has not been tagged

### ISSUE THREAD

**Issue by fusion809** [rudrab/Shadow#23]
Hi,

I've noticed that there are tags for versions &leq;1.5 but not 1.6 in this repo, even though the 1.6 version is the latest release according to this theme's GNOME Look page (http://gnome-look.org/content/show.php/Shadow?content=170398). This is relevant as I have written a PKGBUILD for this theme and placed it in my Open Build Service Arch_Extra Project (http://build.opensuse.org/package/show/home:fusion809:arch_extra/shadow-icon-theme) and it is more convenient for my PKGBUILD to download releases from this repo. With this source variable:

```bash
source=("https://github.com/rudrab/Shadow/archive/v${pkgver}.tar.gz")
```

where `${pkgver}` is, of course, the package version (the latest is 1.6, ofc). 

Thanks for your time,
Brenton

**Comment by rudrab** [comment]
Hi,
Thanks for letting me know. I have added the tag.
Thanks a lot again for packing and maintaining this for arch.

**Comment by rudrab** [comment]
Hi,
Thanks for your effort for packing the iconset.
There is a new minor release(v1.6.2).

**Comment by rudrab** [comment]
hi, 
I have updated Shadow to be compatible with gnome 3.20.
Please have a look.

**Comment by rudrab** [comment]
Hi,
I have seen you are now using git to get the new release, and  not the tar.gz.
In this case, kindly let me know if this issue is still valid.
