### ISSUE TITLE
Two icon requests: for Blockify and Virtual Machine Manager (VMM)

### ISSUE THREAD

**Issue by fusion809** [rudrab/Shadow#24]
Hi,

I would also like to request that two extra icons be added to this theme, one for [Blockify](https://github.com/mikar/blockify) and another for the [Virtual Machine Manager](https://virt-manager.org). 

Thanks for your time,
Brenton

**Comment by rudrab** [comment]
Hi,
Thanks for your request. Can you kindly send me the corresponding icon names as well?

**Comment by fusion809** [comment]
Icon names? You mean their file names as they appear in `.desktop` files? If so, for VMM it is `virt-manager` and for Blockify it is just `blockify`.

**Comment by rudrab** [comment]
Updated. version is now 1.6.1
