### ISSUE TITLE
Icon request: Google Hangouts

### ISSUE THREAD

**Issue by niekez** [rudrab/Shadow#25]
![image](https://cloud.githubusercontent.com/assets/6378007/14138563/212f3ed4-f66e-11e5-9d5b-a5407a0eb606.png)

Thank you.

**Comment by rudrab** [comment]
Hi,
Thanks for your request. I was not aware that chrome can be added in favourite list, and failed to get that.
Hence I do not have any idea about the icon name. Can you kindly give me the icon name?

**Comment by rudrab** [comment]
Hi,
Your icon is ready....please let me know if you have the icon name. It should be in /usr/share/applications/*.desktop or .local/share/applications/*.deskotp

**Comment by niekez** [comment]
That's fast!

The icon name contains the app-id apparently, this was in the desktop file:

Icon=chrome-knipolnnllmklapflnccelgolnpehhpl-Default

For running, this is one of the parameters:
app-id=knipolnnllmklapflnccelgolnpehhpl

So it seems the icon name is chrome-<app-id>-<profile-name>

I hope this was helpful.

Op wo 30 mrt. 2016 om 13:59 schreef rudrab <notifications@github.com>:

**Comment by rudrab** [comment]
Hi, your requested icon is in git...please update

**Comment by niekez** [comment]
It's working, nice icon!

Op wo 30 mrt. 2016 om 14:16 schreef rudrab <notifications@github.com>:
