### ISSUE TITLE
Icon request

### ISSUE THREAD

**Issue by maxnumberone** [rudrab/Shadow#26]
Hello,
Could you please add icons for :
- Master pdf editor (https://code-industry.net/masterpdfeditor/ advanced and closed source pdf editor), icon name of the app is pdfeditor.png
- CPU-X (https://github.com/X0rg/CPU-X grab information about cpu and more) icon name cpu-x
- virt-viewer (https://virt-manager.org/ SPICE client allowing to take control of a virtual machine) icon name virt-viewer
Thanks,
Regards,
Maxime

**Comment by rudrab** [comment]
Hi, Icons are added. Please pull it from the repo.

**Comment by maxnumberone** [comment]
Thanks,
there is a small issue, pdfeditor.png isn't present in the package, I've found only an icon and a link named masterpdfeditor3.svg & png.
Thanks
Regards,
Maxime

**Comment by rudrab** [comment]
oops...my mistake. pdfeditor added(sym. link to masterpdf3)
