### ISSUE TITLE
Request for extra icons: Brackets, Kmenuedit, Komodo Edit, LightTable, RuneScape, SuperTux, Spyder

### ISSUE THREAD

**Issue by fusion809** [rudrab/Shadow#29]
Hi,

I would like to request icons for the following programs (with hyperlinks to the existing icons used on Arch Linux and most other Linux distros):

* [Adobe Brackets](http://brackets.io/) ([icon](https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Brackets_Icon.svg/2000px-Brackets_Icon.svg.png))
* Kmenuedit ([icon](http://imgur.com/25AlXcz.png))
* [Komodo Edit](http://komodoide.com/komodo-edit/) ([icon](https://upload.wikimedia.org/wikipedia/commons/c/c1/Komodo_Edit_icon.png))
* [LightTable](http://lighttable.com/) ([icon](https://upload.wikimedia.org/wikipedia/commons/1/1b/Light_Table_logo.png))
* [RuneScape](https://www.runescape.com/download) ([icon](http://vignette3.wikia.nocookie.net/runescape2/images/d/dc/Game_Client_icon.png/revision/latest?cb=20150330180139))
* [SuperTux](http://supertux.github.io/) ([icon](http://i.utdstc.com/icons/120/supertux-0-3-1d.png))
* [Spyder](https://github.com/spyder-ide/spyder) ([icon](https://avatars0.githubusercontent.com/u/1284937?v=3&s=400))

Thanks for your time,
Brenton

**Comment by rudrab** [comment]
Hi,
Thanks for your request. While I am creating the icons, can you kindly let me know the icon names? These should be available in /usr/share/applications/*.desktop files.
Regards,

**Comment by fusion809** [comment]
Here are the icon names:

* Brackets the icon name is just `brackets`
* Kmenuedit the icon name is just `kmenuedit`
* Komodo Edit, the icon name is a little complicated, on Arch Linux the icon field in my /usr/share/applications/komodo-edit.desktop file is `/opt/komodo-edit/share/icons/komodo48.png`. Guessing `komodo` will be a good enough icon name? 
* LightTable uses the icon name `lighttable`
* RuneScape uses the icon name `runescape`.
* SuperTux uses the icon name `supertux` and `supertux-old`. 
* Spyder uses the icon name `spyder` and `spyder3`.

**Comment by m1rKo** [comment]
First...very very great work! 
I would like to request icons too to complete my desktop:

- [Aptana Studio 3 Core](http://www.aptana.com/) -> [icon](https://avatars3.githubusercontent.com/u/31783?v=3&s=200) ->  `Icon=/opt/Aptana_Studio_3/icon.xpm`
- [Hibiscus Home Banking](https://github.com/willuhn/hibiscus) -> [icon](https://github.com/willuhn/hibiscus/blob/master/icons/hibiscus-icon-64x64.png) -> `Icon=/opt/jameica/jameica-icon.png`
- [Viking GPS Editor](https://sourceforge.net/projects/viking/) -> [icon](https://sourceforge.net/p/viking/code/ci/master/tree/win32/installer/pixmaps/viking_icon.ico) -> `Icon=viking`
- [Puddle Tag](http://docs.puddletag.net/) -> [icon](https://github.com/keithgg/puddletag/blob/master/source/puddlestuff/data/icon.svg) -> `Icon=puddletag
`

Thank you!!

**Comment by rudrab** [comment]
hi m1rKo,
Its great that you like the icon-set.
but can you please open a new issue? Its easier to manage in that case.

**Comment by fusion809** [comment]
Note: I have added Visual Studio Code to my request. I hope I don't have to start a new issue request for it.

**Comment by rudrab** [comment]
fusion809,
your icons are updated, except supertux. I need bit more time on that.
Please pull the git.

**Comment by rudrab** [comment]
Hi fusion809,
visual-studio is already in the git.
Can you please let me know the icon name?

**Comment by fusion809** [comment]
Oops sorry, I didn't notice it. Nvm my VScode request.

**Comment by fusion809** [comment]
Thanks for this, I have just added [`shadow-icon-theme-git`](https://aur.archlinux.org/packages/shadow-icon-theme-git) to the AUR FTW!

**Comment by rudrab** [comment]
good that its working...but I wonder why it was not detected? does VScode uses any different name? if it is so, please let me know, so that I can update.

**Comment by fusion809** [comment]
I'm presently using the `visual-studio-code-oss` AUR package which has a `.desktop` file with the `Icon=` field of:
`/opt/VSCode-OSS/resources/app/resources/linux/code.png`. So I had to modify it to `visual-studio-code`, that's why I didn't see your changes immediately.

**Comment by Dutchman1990** [comment]
I hate to hijack the pull request, but what is the font you've used in that preview image.

**Comment by cbcoutinho** [comment]
It seems that LightTable has since changed the name of its own icon - now it is called lticon.svg

This is from downloading it directly from their website, not using a repository or package manager

**Comment by rudrab** [comment]
Hi,
Sorry to keep you waiting for long. Actually, this particular icon is something I am not happy with. Though I have pushed an icon now, kindly consider it as a place holder (so that it does not look odd among other). Hope, I will come up with a better icon soon. 
Also, please honestly comment how you like the icon.

**Comment by fusion809** [comment]
Well I was expecting an icon where all of Tux was shown, similar to how he is depicted in the official icon, but your eyes and nose-only icon isn't bad either. I could certainly understand the challenges in fitting in a full Tux in an icon that is likely to be displayed quite small on Linux desktops. If you'd like some design ideas for improving the icon, I found this SuperTux icon via a Google Images search, that you might be able to base it on. 

![](https://download.qnap.com/QPKG/images/QPKG/HD_V3_Icon/640/supertux_640.png)
