### ISSUE TITLE
Gnome Commander

### ISSUE THREAD

**Issue by zierlerf** [rudrab/Shadow#3]
Could you please do Gnome Commander? :)

**Comment by rudrab** [comment]
zierlerf : Thanks for using it. gnome commander is now in repo. Hope you will like that.

**Comment by zierlerf** [comment]
Thanks for the quick response, but I can't find it unfortunately.

**Comment by rudrab** [comment]
I am so sorry....I did not realized the push failed. I have pushed it again and checked it is in repo.
May you kindly pull it once again?

**Comment by zierlerf** [comment]
yeah it worked this time! thank you very much!

**Comment by rudrab** [comment]
Thanks. 
I am closing the issue as solved. Feel free to open and comment  if required.
