### ISSUE TITLE
Icon request 

### ISSUE THREAD

**Issue by m1rKo** [rudrab/Shadow#30]
Sorry, heres my post again...in the right place
I would like to request following icons:

- [Aptana Studio 3 Core](http://www.aptana.com/) -> [icon](https://avatars3.githubusercontent.com/u/31783?v=3&s=200) ->  `Icon=/opt/Aptana_Studio_3/icon.xpm`
- [Hibiscus Home Banking](https://github.com/willuhn/hibiscus) -> [icon](https://github.com/willuhn/hibiscus/blob/master/icons/hibiscus-icon-64x64.png) -> `Icon=/opt/jameica/jameica-icon.png`
- [Viking GPS Editor](https://sourceforge.net/projects/viking/) -> [icon](https://sourceforge.net/p/viking/code/ci/master/tree/win32/installer/pixmaps/viking_icon.ico) -> `Icon=viking`
- [Puddle Tag](http://docs.puddletag.net/) -> [icon](https://github.com/keithgg/puddletag/blob/master/source/puddlestuff/data/icon.svg) -> `Icon=puddletag
`
Thank you!!

**Comment by rudrab** [comment]
Hi,
I am not sure how to make Aptana work...unless you edit the .desktop yourself. So, Aptana is not done yet.
Please pull again for the other icons
