### ISSUE TITLE
Icon for .deb files

### ISSUE THREAD

**Issue by armandas** [rudrab/Shadow#31]
At the moment, deb package files are shown as archives. Could you create an icon with a standard debian box to make the packages more distinguishable?

Thanks
Armandas

**Comment by rudrab** [comment]
hi...thanks a lot for pointing this out. this was a big mistake. I have updated it. Please pull it.

**Comment by armandas** [comment]
Thanks for the quick response. This does not seem to work on Ubuntu 16.04. The mime type for the dep package is shown as [`application/vnd.debian.binary-package`](http://manpages.ubuntu.com/manpages/wily/man5/deb.5.html), but I'm not sure how to convert that to the filename.

**Comment by rudrab** [comment]
Hi, 
Can you please search for Icon tag in /usr/share/applications/*deb*.desktop files and let me know the output? 
You can do

grep Icon /usr/share/applications/*deb*.desktop 

and paste the output here. 
Thanks

**Comment by armandas** [comment]
That file does not exist on my system. I can't see anything similar either.

**Comment by armandas** [comment]
Hi. I have checked other themes, and they seem to just use package-x-generic icon (looks like a box). I think the issue is that your package-x-generic.svg looks like an archive, instead of a package.
