### ISSUE TITLE
Icon Request : shadowsocks-qt5

### ISSUE THREAD

**Issue by mcjoeng** [rudrab/Shadow#36]
[Desktop Entry]
Name=Shadowsocks-Qt5
GenericName=Shadowsocks-Qt5
Comment=Shadowsocks GUI client
Exec=ss-qt5
Icon=shadowsocks-qt5
Terminal=false
Type=Application
Categories=Network;
StartupNotify=true

![shadowsocks-qt5](https://cloud.githubusercontent.com/assets/10485304/15317029/503330a0-1c52-11e6-81cc-e75d27408475.png)

### https://github.com/shadowsocks/shadowsocks-qt5

**Comment by rudrab** [comment]
hi,
Thanks for your icon request. All the 4 icons are pushed to git.
Hope, you will like it.

**Comment by mcjoeng** [comment]
@rudrab Thanks you very much. I like this icon-theme so much
