### ISSUE TITLE
Symbolic icons are not gnome-standard

### ISSUE THREAD

**Issue by Linux4Pharmacy** [rudrab/Shadow#38]
take a look at this picture
![screenshot from 2016-05-20 06-24-59](https://cloud.githubusercontent.com/assets/19488957/15425279/45bc90f8-1e55-11e6-9cab-990f635ca72b.png)

I believe, the "back", "forward" and "search" icons should be simpler or plain black. I believe it's easier for the eye to find what it is looking for. 

About the "antialiasing" I mentioned once... I you look closely some icons like "Universal Access" on the above screenshot, look a bit rough around. It may be more visible in this screenshot:

Look at the new/compose e-mail icon
![screenshot from 2016-05-20 06-29-06](https://cloud.githubusercontent.com/assets/19488957/15425381/e25c08c6-1e55-11e6-9b98-ef3327bf1c6f.png)

Please view the screenshots full screen (I use a 1366x768 15,6 inch monitor) and don't zoom because it ruins the way I see it on my screen.

**Comment by rudrab** [comment]
Hi,
Your first observation is really valid, and an artifact of little knowledge when I started building this iconset. Those icons are actually symbolic icons, and have some special properties; which I was not aware of. I am planning to remake those icons in the summer vacation. Stay tuned :).

**Comment by Linux4Pharmacy** [comment]
I can't wait!!!!!

2016-05-20 18:05 GMT+03:00 rudrab <notifications@github.com>:

**Comment by rudrab** [comment]
modified symbolic icons are pushed to repo; give a try.
