### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by jj3666** [rudrab/Shadow#39]
"Add show desktop icon to launcher" needs to have a shadow themed icon? In addition, the new gnome software link (not the old Software Center) is still system default. Maybe just link the Software center to the new one?
![software icon](https://cloud.githubusercontent.com/assets/421542/15630030/30fda54a-24df-11e6-8a30-05727372cd08.png)

![icon request](https://cloud.githubusercontent.com/assets/421542/15630018/bb8d2164-24de-11e6-8e7f-ad64cb783f2e.png)

**Comment by rudrab** [comment]
Hi,
Thanks for your request. 
Are you using ubuntu 16.04? I havn't found the icons you requested in my installation. Can you give me the corresponding icon name? This should be in /usr/share/applications/*.desktop

**Comment by rudrab** [comment]
update pushed.
