### ISSUE TITLE
Icon request

### ISSUE THREAD

**Issue by anonimus-programus** [rudrab/Shadow#4]
Hi Rudra,
great work man.

I use Arch linux, and here new icons to be themed, please.

Avahi SSH Server Browser
Avahi VNC Server Browser
Avahi Zeroconf Browser
avidemux
CMake
CopyQ
Doublw Commander
Florence Virtual Keyboard
GPRename
gThumb
gtkpod
HandBrake
Htop
I-Nex
IcedTea-Web Control Panel
Image Viewer
JACK Rack
Nemo
Network Tools
OpenShot Video Editor
Phototonic
PkgBrowser
pyRenamer
qBittorrent
qScreenshot
Root Terminal
Software Update
Sound Converter
Sublime Text
System Log
TeamViewer
tkPacman
UNetbootin
utext
Workrave
WPS Presentation
WPS Spreadsheets
WPS Writer
Xournal

Thank you.

**Comment by rudrab** [comment]
Hi, 
Thanks. But as I can see, many of them is already themed, may be arch is using a name different from fedora. 
Can you kindly send me the icon name? It is in the /usr/share/applications/*. desktop file. 
Regards,

**Comment by rudrab** [comment]
most of the icons uploaded....can't do much unless you give me the icon names.

**Comment by rudrab** [comment]
Closing it; but feel free to reopen and comment.

**Comment by anonimus-programus** [comment]
Hi Rudra
Sorry for delay, my bad, I was on vacation.

So here they are (42 so far):
Avahi SSH Server Browser (network-wired)
Avahi VNC Server Browser network-wired)
Avahi Zeroconf Browser (network-wired)
avidemux (avidemux)
CMake Qt (CMakeSetup)
CopyQ (copyq)
Double Commander (doublecmd)
File (Nautilus) (system-file-manager)
File Manager PCManFM (system-file-manager)
Florence Virtual Keyboard (/usr/share/pixmaps/florence.svg)
GPRename (gprename)
gThumb (gthumb)
gtkpod (gtkpod)
HandBrake (hb-icon)
Htop (htop)
I-Nex (/usr/share/pixmaps/i-nex-128.png)
IcedTea-Web Control Panel (javaws)
Image Viewer (gpicview)
JACK Rack (jack-rack-icon.png)
Nemo (folder)
Network Tools (gnome-nettool)
OpenShot Video Editor (openshot)
Phototonic (phototonic)
PkgBrowser (pkgbrowser)
pyRenamer (/usr/share/pyrenamer/pyrenamer.png)
qBittorrent (qbittorrent)
qScreenshot (screenshot)
QuiteRSS (quiterss)
Root Terminal (gksu-root-terminal)
Software Update (system-software-update)
Sound Converter (soundconverter)
Sublime Text 3 Dev (sublime-text)
System Log (logview)
TeamViewer 10 (/opt/teamviewer/tv_bin/desktop/teamviewer.png)
tkPacman (/usr/share/tkpacman/icons/tkpacman-icon.png)
UNetbootin (unetbootin)
utext (/opt/extras.ubuntu.com/utext/share/utext/icons/utext.svg)
Workrave (workrave)
WPS Presentation (wps-office-wppmain)
WPS Spreadsheets (wps-office-etmain)
WPS Writer (wps-office-wpsmain)
Xournal (xournal)

Thanks

**Comment by rudrab** [comment]
Hi,
Thanks for providing the icon names. Few of them can not be themed as they are showing absolute path (unless you change the corresponding .desktop file), e.g. utext (/opt/extras.ubuntu.com/utext/share/utext/icons/utext.svg). I will update the rest of them very soon.

**Comment by rudrab** [comment]
Hi,
Its updated.
Please check again.

**Comment by rudrab** [comment]
Hi,
Another update and all of the requested icons are pushed to github. Kindly update it.
May I request you a vote in gnome-look?

**Comment by anonimus-programus** [comment]
Thanks, updated.

And you have my vote. :D

**Comment by rudrab** [comment]
thanks a lot.
