### ISSUE TITLE
workspace indicator icon request

### ISSUE THREAD

**Issue by Dickby** [rudrab/Shadow#40]
Hi, it would be nice to have a matching Icon for the gnome-shell-extension "workspace indicator".
Thanks!!

**Comment by rudrab** [comment]
Hi,
I installed the extension to check what I can do, and find that the symbol is actually a css, and not actually a image. So, there is nothing much I can do, except a hack.

Here is a minor hack to the workspace-indicator code:
Replace `local/share/gnome-shell/extensions/workspace-indicator@gnome-shell-extensions.gcampax.github.com/stylesheet.css` with this:
```.
.panel-workspace-indicator {
	padding: 0 8px;
	background-color: rgba(200, 200, 200, .5);
	border: 1px solid #cccccc;
        border-radius: 25px;
}

```

**Comment by Dickby** [comment]
That works for me! 
Thanks a lot
