### ISSUE TITLE
FontForge and font file icons (and other requests)

### ISSUE THREAD

**Issue by skalyan91** [rudrab/Shadow#41]
Thanks for making such a beautiful and complete iconset! It's drawing me ever-closer towards switching from Mac to Linux.

One app icon I would definitely need is for FontForge; likewise, I would need mimetype icons for font formats other than TTF (e.g. OTF, SFD, UFO, PFB).

Other app icons I would find useful (in decreasing order of priority) are:
* R and Rstudio
* Gummi and LyX
* Praat
* Qterminal and Terminix
* OpenAstro and Maitreya

Other mimetype icons I would find useful are for vimscript (`.vim`), haskell (`.hs` or `.lhs`), and APL (`.apl`).

Thanks!

**Comment by rudrab** [comment]
Hi,
Thanks that you like the iconset.
R filetype is already themed. But as for the apps, can you kindly add the corresponding icon names? you will most probably get them in the `ICon` key in `/usr/share/applications/*.desktop `.

**Comment by skalyan91** [comment]
The icon names for these apps are:
* `fontforge.ico`
* `R.ico`
* `RStudio.ico`
* `gummi.ico`
* `lyx.ico`
* probably `praat.ico`—not entirely sure
* `utilities-terminal` for Qterminal (so no need to make a new icon, I guess)
* `com.gexperts.Terminix`
* `openastro.svg`
* `maitreya.ico`

**Comment by skalyan91** [comment]
Would also like the following two icons:
* Frescobaldi (`frescobaldi`)
* Denemo (`denemo`)

**Comment by skalyan91** [comment]
Thanks—all beautiful!

I would still need the font-format mimetypes (`.otf`, `.sfd`, `.ufo`, `.pfa`, `.pfb`)—unless you think these are adequately covered by the `font-x-generic` mimetype, in which case I won't argue with that decision.

The `.apl` mimetype would still be desirable (though not really a top priority).

**Comment by rudrab** [comment]
Hi,
Generic font does not cover all the font types, I agree with that. But, for completeness, if I do specific type icons, I have to do the same for other generic types as well(e.g. movies and images). Its on my to do list, and I am trying to do that by this summer.

Also sorry, I missed the apl mime type. But are you sure the linux supports apl mimetype? I mean I need to know that for the name (application/text catagory)

**Comment by skalyan91** [comment]
I assume that since GNU APL runs on Linux, the `.apl` mimetype should be supported by Linux.

Also, another filetype I forgot is LilyPond source files, which are `.ly`. These are used by musical score editing applications such as the ones mentioned above.

I guess it does make sense to do all the specific file types all at once. No hurry, then.
