### ISSUE TITLE
Icon request

### ISSUE THREAD

**Issue by Dickby** [rudrab/Shadow#43]
It would be nice to have an Icon for Dosbox

**Comment by rudrab** [comment]
Hi,
Can you, as requested, give me the icon name? Also, is it possible for you to show me how the icon looks like?

**Comment by Dickby** [comment]
the name of the icon is dosbox (on my computer located in /usr/share/pixmaps/dosbox.png:
![dosbox](https://cloud.githubusercontent.com/assets/10100765/16901579/f5a02d34-4c47-11e6-8f9e-0269db650473.png)

**Comment by rudrab** [comment]
Hi Dickby,
Thanks for yot reply. But, it would have been better if you can show paste the Icon tag from `/usr/share/applications/dosbox.desktop` (the default position if you have installed it from your app manager eg apt-get/dnf etc)

**Comment by rudrab** [comment]
Btw, the icon is ready...but I am not sure if it will work out of the box if the .desktop file uses the absolute path. You may have to add the icon yourself.
You can update the icon theme from git pull.
And please, consider upvoteing the theme in gnome-looks.
Thanks.

**Comment by Dickby** [comment]
It works, Thanks for that.
I already upvoted the theme on gnome-look.
I close this issue
