### ISSUE TITLE
Icons Request: Cockatrice, Franz, RStudio, Spyder3, Spyder, Zotero

### ISSUE THREAD

**Issue by brenoec** [rudrab/Shadow#44]
Hello there,

I would like shadow master icons for Cockatrice, Franz, RStudio, Spyder3, Spyder, Zotero. Spyder3 and Spyder icons are identical, so I omitted one of them in the image.

**Icons**

![image](https://cloud.githubusercontent.com/assets/780572/17841846/49281090-67f3-11e6-80d9-9665cf77e448.png)

**Icons' names**
- cockatrice
- franz
- rstudio
- spyder3
- spyder
- zotero

_Sorry, I was unable to label this as Icon Request. Reason: knowledge nonexistent, and google didn't work for me this late. I guess I'm no contributor and don't know how to become one._

Thanks,
Breno Souza

**Comment by rudrab** [comment]
Hi brenoec,
Thanks for your icons. But spyder[3] is already in the repo; and so is rstudio.  Kindly check. Rest of them will be updated soon.

**Comment by rudrab** [comment]
Hi,
icons are pushed. Please try them; and consider up-vote at gnome-looks, if you like the theme.

**Comment by brenoec** [comment]
WOW, ASAP indeed!

I missed the existent ones because I installed another package with this set. I followed the guides in this repository and they are there now. Sorry for the trouble.

They look great, thanks! Consider yourself up-voted: when I return to home I'll do it! I have an e-mail to remember me.

Thanks again,
Breno Souza
