### ISSUE TITLE
Icon request

### ISSUE THREAD

**Issue by m1rKo** [rudrab/Shadow#45]
Hey! I want to request some more icons:

- Hamster Time Tracker : `hamster-time-tracker` : [icon](https://raw.githubusercontent.com/projecthamster/hamster/master/data/art/scalable/hamster-time-tracker.png)
- dupeGuru Music Edition : `dupeguru_me` : [icon](https://raw.githubusercontent.com/hsoft/dupeguru/master/images/dgme_logo_128.png)
- dupeGuru Picture Edition : `dupeguru_pe` : [icon](https://raw.githubusercontent.com/hsoft/dupeguru/master/images/dgpe_logo_128.png)
- dupeGuru Standard Edition : `dupeguru_se` : [icon](https://raw.githubusercontent.com/hsoft/dupeguru/master/images/dgse_logo_128.png)
- Genius Math Tool : `gnome-genius` : [icon](https://github.com/GNOME/genius/blob/master/pixmaps/256x256/gnome-genius.png)
- Slack : `slack` : [icon](https://blog.agilebits.com/wp-content/uploads/2014/09/Slack-icon.png)
- yEd Graph Editor : `yEd` : [icon](https://www.macupdate.com/images/icons256/36897.png)

Thank you a lot!!!

**Comment by rudrab** [comment]
Hi...sorry..I missed your request.
It will be updated soon.

**Comment by rudrab** [comment]
updated. Please pull it again from github.
