### ISSUE TITLE
Icon request - YaST package manager

### ISSUE THREAD

**Issue by cbcoutinho** [rudrab/Shadow#46]
I would like to make a request for you to create a Shadow version of the openSUSE package manager application: YaST

![](https://upload.wikimedia.org/wikipedia/commons/3/34/YaST_logo.png)

As you requested in previous issues, YaST.desktop looks like this:

```
[Desktop Entry]
Type=Application
Categories=Settings;System;X-SuSE-Core-System;X-SuSE-ControlCenter-System;X-GNOME-SystemSettings;
Name=YaST
Icon=yast
GenericName=Administrator Settings
Exec=/usr/bin/xdg-su -c /sbin/yast2
Encoding=UTF-8
Comment=Manage system-wide settings
```

**Comment by rudrab** [comment]
Thank you very much for your request. I will update it ASAP.

**Comment by rudrab** [comment]
Hi,
yast is added to the repo. Please pull it from github.
Dont forget to upvote in gnome-looks.
Thnaks.
