### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by SirMartyMcFly** [rudrab/Shadow#47]
Enpass password manager

**Comment by rudrab** [comment]
hi,
thanks for the icon request.
Please, attach the corresponding .desktop file

**Comment by Adam-Morris** [comment]
.desktop file:
https://drive.google.com/file/d/0BwdYyT-EJPqCV2wyMEtRVFZOMGs/view

**Comment by SirMartyMcFly** [comment]
YAAAAAAAAS! Thank you.

**Comment by rudrab** [comment]
Thanks Adam.
Done
