### ISSUE TITLE
Icon request: applications-education-science, boswars, konversation, mathematica, notepadqq and warzone2100

### ISSUE THREAD

**Issue by fusion809** [rudrab/Shadow#49]
Hi,

Sorry if I'm overwhelming ya with icon requests but I would like to request the following icons:

* `applications-education-science` (which is the exact icon name I'd suggest, to be used for application menus), [here](https://commons.wikimedia.org/wiki/File:Antu_applications-education-science.svg) is an example icon from the Antu icon set. 
* `boswars`
* `konversation`
* `mathematica`
* `notepadqq`
* `warzone2100`

Thanks for your time,
Brenton

**Comment by fusion809** [comment]
@rudrab Don't meant to be pushy, but I was just wondering if this icon request likely to be acted on soon?

**Comment by rudrab** [comment]
Hi, 
Few of the icons are done,  I will push them.  The icons for the games will take some more time, as I am going through a death in my family.

**Comment by fusion809** [comment]
Ah sorry and thanks for the push.

**Comment by rudrab** [comment]
pushed. Please pull it.
