### ISSUE TITLE
top nav bar setting icon and volume icon not displayed 

### ISSUE THREAD

**Issue by rajmani1995** [rudrab/Shadow#5]
OS version -> Ubuntu 15.04
settings and volume icons just showing blank.

**Comment by rudrab** [comment]
Hi,
Thanks for reporting this bug. Unfortunately, I don't have access to Ubuntu 15.04. In 15.10, I checked its working well. I am bit confused, as the volume icons (in topbar) is not themed at all.
So, to solve the problem, can you kindly check this with Adwita (default icon), and also let me know if you are using gnome(which version)/unity?
Regards,
RudraB

**Comment by rudrab** [comment]
To be specific, I have tried it with Ubuntu-Gnome 3.10 and Ubuntu Unity 3.10. Both are showing there default icon for volume. System settings icon is also from Shadow, and not going blank.

**Comment by rudrab** [comment]
Hi, 
I have managed to reproduce the problem in gnome-Unity. This problem occurs in Unity only, and not in gnome distro. But, I have added the solution for it. Please check and comment.
I am closing the issue now. Please feel free to reopen if you are still facing the same problem
