### ISSUE TITLE
Icon request - GitKraken + Dropbox

### ISSUE THREAD

**Issue by cbcoutinho** [rudrab/Shadow#50]
Howdy @rudrab,

Thanks for being so up-to-date on these icon requests. Here are two more if you have the time. Again, no rush.

- `GitKraken` - A git client gui for windows, mac, and linux. This one is strange because it normally doesn't come with an icon in the distributed binaries. I had to download an icon, put it in the gitkraken directory, and link to it in the gitkraken.desktop file I have under /home/chris/.local/share/applications/gitkraken.desktop - I'm not sure if you want to mess around with something so hackish - I'd like your input regardless. This is what it looks like:

```
[Desktop Entry]
Comment=The downright luxurious Git client, for Windows, Mac & Linux
Terminal=false
Name=GitKraken
Exec=/home/chris/Projects/GitKraken/gitkraken
Type=Application
Icon=/home/chris/Projects/GitKraken/gitkraken.png
```

![gitkraken](https://cloud.githubusercontent.com/assets/12901868/18726220/bef4dd2c-8043-11e6-973d-48ff9700e7db.png)

- `Dropbox` - online digital storage. Currently all sub-directories in my home directory use the footprint icon, whereas the dropbox directory (/home/chris/dropbox/) ususally has its own icon. Since this isn't an application, I'm not sure where the icon normally resides, or if the dropbox daemon overrides the folder icon on the other default icon themes. Would also like your input on this one.

![dropbox](https://cloud.githubusercontent.com/assets/12901868/18726315/272614e2-8044-11e6-8278-6c3a65c7337e.png)

Much respect for putting this out there!

**Comment by rudrab** [comment]
Hi,
Thanks for your icon requests. I will add the Gitkraken ASAP.
But, dropbox folder is already there. As far as in gnome, you have to choose the icon manually. `Right click on Dropbox folder`->`properties`->`click on icon` and select `~/.icons/shadow/scalable/places/folder-dropbox.svg`

**Comment by rudrab** [comment]
Hi,
GitKraken is pushed. But, the file is not in standard location. Please, change the icon to `gitkraken` only, and it should work. Dint hesitate to contact me if you need further help.

**Comment by cbcoutinho** [comment]
Thanks for the quick reply and for taking up the issue request.

Is it normal behavior that setting the Dropbox icon manually removes the dropbox sync status?

**Comment by cbcoutinho** [comment]
Thanks, that was fast. Changing the icon name to `gitkraken` seems to have done the trick.

Cheers!
