### ISSUE TITLE
Icon request - WMail

### ISSUE THREAD

**Issue by cbcoutinho** [rudrab/Shadow#51]
Howdy @rudrab,

Just a quick icon request from you: [WMail](http://thomas101.github.io/wmail/)

<a href="url"><img src="https://cloud.githubusercontent.com/assets/12901868/18859629/1c5d0332-8476-11e6-83a9-1630e897b1c1.png" width="100" ></a>

link: https://cloud.githubusercontent.com/assets/12901868/18859629/1c5d0332-8476-11e6-83a9-1630e897b1c1.png

```
[Desktop Entry]
Comment=The missing desktop client for Gmail & Google Inbox
Terminal=false
Name=WMail
Exec=/home/chris/Projects/WMail-linux-x64/WMail
Type=Application
Icon=/home/chris/Projects/WMail-linux-x64/resources/app/bin/icons/app.png
```

I would propose changing the name of the icon to `wmail.png` or something, but if you download the source from their website they use the slightly ambiguous `app.png`

**Comment by rudrab** [comment]
icon is updated. please pull it again

**Comment by cbcoutinho** [comment]
Looks great, thanks again!
