### ISSUE TITLE
Icon request - Matlab

### ISSUE THREAD

**Issue by cbcoutinho** [rudrab/Shadow#52]
Another icon request if you have time:

Matlab

![matlabicon_256](https://cloud.githubusercontent.com/assets/12901868/19074516/ccf0a4cc-8a40-11e6-8aef-a7ca97a1ff0f.png)

**Comment by rudrab** [comment]
hi, please provide me the .desktop file, in lnux, generally available at /usr/share/applications

**Comment by rudrab** [comment]
icon is updated. please pull it again
