### ISSUE TITLE
Icon request - ParaView

### ISSUE THREAD

**Issue by cbcoutinho** [rudrab/Shadow#53]
I have a icon request for you regarding the scientific visualization application, ParaView:

![paraview](https://cloud.githubusercontent.com/assets/12901868/19388932/30599648-9222-11e6-9180-d195bb43a6db.png)

The associated .desktop file I use is as follows
```
[Desktop Entry]
Version=5.2.0-RC1
Type=Application
Name=ParaView
Comment=Parallel visualization application
TryExec=paraview
Icon=paraview
```

Thanks in advance man, your icons are helping my system look great

**Comment by rudrab** [comment]
Done. Please pull it.

**Comment by cbcoutinho** [comment]
Looks great!
