### ISSUE TITLE
icon request

### ISSUE THREAD

**Issue by Dickby** [rudrab/Shadow#54]
There are no icons for 'zenmap' and 'Qt V4L2 test Utility'.
Thanks

**Comment by rudrab** [comment]
Hi, 
Thnaks for your request.
Zenmap is already themed. Can you post me your `/usr/share/applications/zenmap.desktop`'s Icon name here? may be there is a name missmatch

**Comment by Dickby** [comment]
the file in my case is zenmap.desktop, the Icon name is zenmap.png and the applications name is Zenmap. I hope this is the information you asked for.

**Comment by rudrab** [comment]
Hi,
Now I understand the problem. Any file name extension in icon field is non-standard, that is why it has not been picked. You can try removing the .png from the icon and it will work fine.

Sent from Alto

________________________________
On Sunday, 18 December 2016 at 11:37 Dickby <notifications@github.com> wrote:


the file in my case is zenmap.desktop, the Icon name is zenmap.png and the applications name is Zenmap. I hope this is the information you asked for.

**Comment by Dickby** [comment]
if i remove the .png in the .desktop file there is no Icon at all for zenmap.
Or should i rename the png file?

**Comment by rudrab** [comment]
this is odd.
The line should be:
Icon=zenmap

Here is my full .desktop file in fedora:
cat /usr/share/applications/nmap-zenmap.desktop
[Desktop Entry]
Name=Zenmap
GenericName=Nmap Security Scanner
Comment=GUI frontend for Nmap security/port scanner
Version=1.0
TryExec=zenmap-root
Exec=zenmap-root
Icon=zenmap
Terminal=false
Type=Application
Categories=System;Security;GTK;X-Red-Hat-Base;
X-Desktop-File-Install-Version=0.23

**Comment by Dickby** [comment]
In my zenmap.desktop file the line was
Icon=/usr/share/zenmap/pixmaps/zenmap.png,
after changing it to
Icon=zenmap without the path it works!
Thanks a lot.

**Comment by rudrab** [comment]
Hi,
One more thing: as you can understand, no icon can give you the icons in absolute path; so with that `Icon=/usr/share/zenmap/pixmaps/zenmap.png`, it will not work with any icon set. As you have edited it, its working fine now. But as soon as your zenmap get updated (`apt-get update` or similar), it will overwrite your change. 

To make it permanent, copy your edited `zenmap.desktop` file to `~/.local/share/applications`. In that case, it will not be updated; until you reinstall your system.

Hope this helps.

**Comment by Dickby** [comment]
Thanks!

**Comment by rudrab** [comment]
Dickby,
Sorry but I have overlooked your "Qt V4L2 test Utility" icon request.
Can you send me the icon name, and if possible, the image?

**Comment by Dickby** [comment]
the icon name is qv4l2, 
and this is how it looks like :
![qv4l2](https://cloud.githubusercontent.com/assets/10100765/21577322/3974e15c-cf57-11e6-9e1d-1437881d7c39.png)
