### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by Adam-Morris** [rudrab/Shadow#56]
Sublime Text 2

**Comment by rudrab** [comment]
Hi,
Thanks for the icon request.
Can you please give me the exact icon name?(may be the .desktop file) and the icon, if possible?

**Comment by Adam-Morris** [comment]
The icon (for me) is located in "/opt/sublime-text/Icon" and here is the .desktop file: https://drive.google.com/file/d/0BwdYyT-EJPqCenRwYktZWGJrSkU/view

**Comment by rudrab** [comment]
sublime_text is added. Please pull it.
Also, please upvote me at [gnome-looks](https://www.gnome-look.org/content/show.php/Shadow?content=170398) if you like the theme.
