### ISSUE TITLE
Missing icons for D language

### ISSUE THREAD

**Issue by jolkdarr** [rudrab/Shadow#6]
Icons should be provided for the following mimetypes:
```
application/x-dsrc
application/x-ddsrc (link)
application/x-disrc (link)
```
Example of icon (actually: svg file):
![application-x-dsrc.svg](https://cloud.githubusercontent.com/assets/3129230/11450898/30e3d128-95b1-11e5-9dc9-363108264081.png)

**Comment by rudrab** [comment]
Hi,
dsrc icons are added. Please pull it.
Also feel free to reopen the thread if you feel any problem

**Comment by jolkdarr** [comment]
Thanks for the new icons and for the theme of course :+1:
