### ISSUE TITLE
Icon Request: Fritzing

### ISSUE THREAD

**Issue by Adam-Morris** [rudrab/Shadow#63]
## **Fritzing**
[.desktop file](https://drive.google.com/open?id=0BwdYyT-EJPqCR1RybHNKMXVIckk)

**Comment by rudrab** [comment]
Can you show me the default icon please?

**Comment by Adam-Morris** [comment]
[icon

**Comment by Adam-Morris** [comment]
[icon](https://cdn.sparkfun.com/assets/5/3/4/3/1/52b1e48a757b7f28448b4567.png)
