### ISSUE TITLE
Icon Request: Gitter

### ISSUE THREAD

**Issue by Adam-Morris** [rudrab/Shadow#69]
## **Gitter**
[.desktop file](https://drive.google.com/open?id=0BwdYyT-EJPqCQl9ibkpjSFR3a2s)

**Comment by rudrab** [comment]
Hi,
as you can see, the icon is not generic, and lives inside the code.
`Icon=/opt/Gitter/linux64/logo.png
`
So, unless you/the maintainer(if any) changes the .desktop file, the app is not themeable.
