### ISSUE TITLE
icon request

### ISSUE THREAD

**Issue by murpholinox** [rudrab/Shadow#71]
Mathematica https://www.wolfram.com/mathematica/
Avogadro http://avogadro.cc/wiki/Main_Page
MyPaint http://mypaint.org/
FocusWriter https://gottcode.org/focuswriter/
Pomodoro http://gnomepomodoro.org/

**Comment by rudrab** [comment]
Hi, 
Thanks for your requests. But Mathematica is already themed. Can you please check the .desktop file for the icon name of mathematica?

**Comment by murpholinox** [comment]
With respect to the Mathematica icon, you are right. (I guess I get confused with the icon being a square, while most of them are circles).

**Comment by rudrab** [comment]
Oops... It is circular. Please share at least the Icon line of your .desktop file

Sent from Alto

________________________________
On Wednesday, 18 January 2017 at 05:53 murpholinox <notifications@github.com> wrote:


With respect to the Mathematica icon, you are right. (I guess I get confused with the icon being a square, while most of them are circles).

**Comment by murpholinox** [comment]
-----------------------------------
Focus writer
-----------------------------------
[Desktop Entry]
Type=Application
Name=FocusWriter
Name[cs]=FocusWriter
Name[da]=FocusWriter
Name[de]=FocusWriter
Name[el]=FocusWriter
Name[en_GB]=FocusWriter
Name[eo]=FocusWriter
Name[es]=FocusWriter
Name[es_MX]=FocusWriter
Name[fi]=FocusWriter
Name[fr]=FocusWriter
Name[he]=FocusWriter
Name[hu]=FocusWriter
Name[hy]=FocusWriter
Name[id]=FocusWriter
Name[ja]=FocusWriter
Name[ko]=포커스 라이터
Name[lt]=FocusWriter
Name[nl]=FocusWriter
Name[pl]=FocusWriter
Name[pt]=FocusWriter
Name[pt_BR]=FocusWriter
Name[ro]=FocusWriter
Name[ru]=FocusWriter
Name[sr]=FocusWriter
Name[sv]=FocusWriter
Name[tr]=FocusWriter
Name[uk]=FocusWriter
Name[vi]=FocusWriter
Name[zh_CN]=FocusWriter
Name[zh_TW]=FocusWriter
GenericName=Fullscreen Word Processor
GenericName[cs]=Celoobrazovkový editor textu
GenericName[da]=Tekstbehandlingsprogram i fuld skærm
GenericName[de]=Vollbild-Textverarbeitung
GenericName[el]=Επεξεργαστής Κειμένου σε Πλήρης Οθόνη
GenericName[en_GB]=Full-screen Word Processor
GenericName[eo]=Plenekrana Tekstoprilaborilo
GenericName[es]=Procesador de textos a pantalla completa
GenericName[es_MX]=Procesador de palabras en pantalla completa
GenericName[fi]=Koko näytön tekstinkäsittelyohjelma
GenericName[fr]=Traitement de texte plein écran
GenericName[he]=מעבד תמלילים במסך מלא
GenericName[hu]=Teljesképernyős szövegszerkesztő
GenericName[hy]=Լիէկրան տեքստային խմբագրիչ
GenericName[id]=Layar Penuh
GenericName[ja]=フルスクリーン・ワードプロセッサ
GenericName[ko]=풀스크린 워드 프로세서
GenericName[lt]=Viso Ekrano Žodžių Doroklė
GenericName[nl]=Volscherm tekstverwerker
GenericName[pl]=Pełnoekranowy edytor tekstów
GenericName[pt]=Processador de texto em ecrã completo
GenericName[pt_BR]=Processador de texto em tela cheia
GenericName[ro]=Procesor de text pe tot ecranul
GenericName[ru]=Полноэкранный текстовый редактор
GenericName[sr]=Обрађивач текста у пуном екрану
GenericName[sv]=Ordbehandlare med helskärmsläge
GenericName[tr]=Tam Ekran Kelime İşlemci
GenericName[uk]=Повноекранний текстовий редактор
GenericName[vi]=Phần mềm soạn thảo văn bản dạng toàn màn hình
GenericName[zh_CN]=全屏文本编辑器
GenericName[zh_TW]=全螢幕文字處理器
Comment=Write without distractions
Comment[cs]=Pište bez rozptylování
Comment[da]=Skriv uden at blive distraheret
Comment[de]=Schreibe ohne Ablenkung
Comment[el]=Γράψτε χωρίς ενόχληση
Comment[en_GB]=Write without distractions
Comment[eo]=Skribu sen malatentigoj
Comment[es]=Escriba sin distracciones
Comment[es_MX]=Escriba sin distractores
Comment[fi]=Kirjoita ilman häiriötekijöitä
Comment[fr]=Écrivez sans distractions
Comment[he]=כתיבה ללא הסחות דעת
Comment[hu]=Írjon zavartalanul
Comment[hy]=Գրիր առանց ուշադրության շեղման
Comment[id]=Menulis tanpa gangguan
Comment[ja]=気を散らすことなく集中して文章を書けるワードプロセッサです
Comment[ko]=글쓰기에 집중할 수 있는 
Comment[lt]=Rašykite be blaškymosi
Comment[nl]=Schrijf zonder afleiding
Comment[pl]=Pisz bez zakłóceń
Comment[pt]=Escreva sem distrações
Comment[pt_BR]=Escreva sem distrações
Comment[ro]=Scrieţi fără distrageri
Comment[ru]=Писать не отвлекаясь
Comment[sr]=Пишите без ометања
Comment[sv]=Skriv utan distraktioner
Comment[tr]=Dikkat dağıtıcılar olmadan yazın
Comment[uk]=Писати не відволікаючись
Comment[vi]=Không tạo sự xao nhãng khi viết
Comment[zh_CN]=专心致志地写作
Comment[zh_TW]=專心寫作
Icon=focuswriter
TryExec=focuswriter
Exec=focuswriter %F
Terminal=false
MimeType=application/rtf;application/vnd.oasis.opendocument.text;application/vnd.openxmlformats-officedocument.wordprocessingml.document;text/plain;text/rtf;
Categories=Qt;Office;WordProcessor;
Keywords=fullscreen;editor;typewriter;keyclick;distraction;concentration;focused;monomaniacal;writing;
-----------------------------------
my paint
-----------------------------------
[Desktop Entry]
Version=1.0
Name=MyPaint
TryExec=mypaint
Exec=mypaint %f
Comment=Painting program for digital artists
Comment[ro]=Software de artă plastică digitală
Comment[fr]=Logiciel de peinture numérique pour artistes
Comment[nn_NO]=Måleprogram for digitale artistar
Comment[nb_NO]=Maleprogram for digitale artister
Comment[zh_CN]=艺术家的电脑绘画
Comment[zh_TW]=藝術家的电脑绘画
Comment[zh_HK]=藝術家的电脑绘画
GenericName=Raster Graphics Editor
GenericName[fr]=Éditeur d'Image Matricielle
MimeType=image/openraster;image/png;image/jpeg;
Type=Application
Icon=mypaint
StartupNotify=true
Categories=Graphics;GTK;2DGraphics;RasterGraphics;
Terminal=false
X-Desktop-File-Install-Version=0.22
-----------------------------------
avogadro
-----------------------------------
[Desktop Entry]
Name=Avogadro
GenericName=Advanced molecular editor
GenericName[el]=Προχωρημένος μοριακός επεξεργαστής
GenericName[fi]=Kehittynyt molekyylimuokkain
GenericName[pt]=Editor molecular avançado
GenericName[ru]=Продвинутый молекулярный редактор
GenericName[tr]=Gelişmiş Moleküler Düzenleyici
GenericName[af]=Gevorderde molekulêre redigeerder
GenericName[sq]=Modifikues i avancuar molekulash
GenericName[ast]=Editor molecular avanzáu
GenericName[eu]=Editore molekular aurreratua
GenericName[be]=Прасунуты рэдактар малекул
GenericName[bn]=উচ্চ পর্যায়ের মলিকুলার সম্পাদক
GenericName[bs]=Napredni uređivač molekula
GenericName[pt_BR]=Editor molecular avançado
GenericName[bg]=Редактор на молекули с много възможности
GenericName[ca]=Editor molecular avançat
GenericName[ca@valencia]=Editor molecular avançat
GenericName[zh_HK]=進階分子編輯器
GenericName[zh_CN]=高级分子编辑器
GenericName[zh_TW]=進階分子編輯器
GenericName[crh]=Gelişmiş moleküler editör
GenericName[cs]=Pokročilý molekulární editor
GenericName[da]=Avanceret molekulær redigering
GenericName[nl]=Geavanceerde moleculaire editor
GenericName[eo]=Prospertula molekulredaktilo
GenericName[et]=Täiustatud molekulaar redaktor
GenericName[fr]=Éditeur moléculaire avancé
GenericName[fr_CA]=Éditeur moléculaire avancé
GenericName[gl]=Editor de moléculas avanzado
GenericName[de]=Fortgeschrittene Molekülbearbeitung
GenericName[he]=עורך מולקולארי מתקדם
GenericName[hi]=उन्नत अणु संपादक
GenericName[hu]=Fejlett molekuláris szerkesztő
GenericName[id]=Penyunting molekul tingkat lanjut
GenericName[it]=Un editor molecolare avanzato
GenericName[ja]=先進的な分子構造エディター
GenericName[ky]=Жакшыртылган молекулалар редактору
GenericName[ko]=고급 분자 편집기
GenericName[ms]=Penyunting molekul termaju
GenericName[nb]=Avansert behandler av molekyler
GenericName[oc]=Editor molecular avançat
GenericName[fa]=ویرایشگر مولکولی پیشرفته
GenericName[pl]=Zaawansowany edytor molekuł i biomolekuł
GenericName[ro]=Editor molecular avansat
GenericName[sr]=Напредни молекуларни уредник
GenericName[sk]=Pokročilý editor molekúl
GenericName[sl]=Napredni urejevalnik molekul
GenericName[es]=Editor molecular avanzado
GenericName[sv]=Avancerad molekylredigerare
GenericName[tg]=Муҳаррири молекулярии пешрафта
GenericName[ta]=மேம்பட்ட மூலக்கூறு திருத்தி
GenericName[th]=ตัวแก้ไขโมเลกุลขั้นสูง
GenericName[uk]=Розширений молекулярний редактор
GenericName[vi]=Trình biên soạn phân tử đa năng
Comment=Molecular Graphics and Modelling System
Comment[da]=Molekulært grafik- og modelsystem
Comment[de]=System für Molekülgrafiken und -modellierung
Comment[fr]=Système de modélisation et d'imagerie moléculaire
Comment[it]=Sistema di grafica e modellamento molecolare
Comment[pl]=System do molekularnego modelowania i wizualizacji
Comment[ru]=Система для молекулярного моделирования и визуализации
Exec=avogadro %f
Icon=avogadro-icon
Terminal=false
Type=Application
Categories=Qt;Science;Chemistry;Physics;Education;
StartupNotify=true
MimeType=chemical/x-cif;chemical/x-cml;chemical/x-daylight-smiles;chemical/x-gamess-input;chemical/x-gamess-output;chemical/x-gaussian-log;chemical/x-mopac-out;chemical/x-pdb;chemical/x-xyz;chemical/x-gaussian-checkpoint;chemical/x-gaussian-cube;chemical/x-qchem-output;
X-Desktop-File-Install-Version=0.23
-----------------------------------
pomodoro
-----------------------------------
[Desktop Entry]
Name=Pomodoro
Name[ca]=Pomodoro
Name[cs]=Pomodoro
Name[de]=Pomodoro
Name[es]=Pomodoro
Name[fa]=پومودورو
Name[fr]=Pomodoro
Name[pl]=Pomodoro
Name[pt_BR]=Pomodoro
Name[ru]=Помодоро
Name[tr]=Pomodoro
Comment=A simple time management utility
Comment[ca]=Una senzilla utilitat de gestió del temps
Comment[de]=Ein einfaches Werkzeug für Zeitmanagement
Comment[es]=Una sencilla utilidad de gestión del tiempo
Comment[fa]=یک ابزار مدیریت زمان ساده
Comment[fr]=Un outils simple de gestion du temps
Comment[pl]=Proste narzędzie do zarządzania czasem
Comment[pt_BR]=Uma ferramenta simples para gerenciar o tempo
Comment[ru]=Простой инструмент для тайм-менеджмента
Comment[tr]=Basit bir zaman yönetimi aracı
Keywords=timer;
Exec=gnome-pomodoro
Icon=gnome-pomodoro
StartupNotify=false
Terminal=false
Type=Application
Categories=GTK;GNOME;Utility;Clock;
X-GNOME-UsesNotifications=true
DBusActivatable=true

**Comment by murpholinox** [comment]
[Desktop Entry]
Version=1.0
Type=Application
Name=Mathematica 11
Comment=Technical Computing System
TryExec=/usr/local/Wolfram/Mathematica/11.0/Executables/Mathematica
Exec=/usr/local/Wolfram/Mathematica/11.0/Executables/Mathematica %F
Icon=wolfram-mathematica
MimeType=application/mathematica;application/x-mathematica;application/vnd.wolfram.nb;application/vnd.wolfram.cdf;application/vnd.wolfram.player;application/vnd.wolfram.mathematica.package;application/vnd.wolfram.wl;x-scheme-handler/wolfram+cloudobject;x-scheme-handler/wolframmathematica+cloudobject;

**Comment by rudrab** [comment]
I have pushed the icons. Please pull and check if it looks better.

**Comment by murpholinox** [comment]
Done. It looks better. Thanks a lot, that was really quick.




2017-01-20 2:40 GMT-06:00 rudrab <notifications@github.com>:
