### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by Apopatos** [rudrab/Shadow#72]
1) **Fedy**
#!/usr/bin/env xdg-open
[Desktop Entry]
Name=Fedy
GenericName=Fedy
Icon=fedy
Comment=Software, Codec Installs & System Tweaks
Exec=fedy
Terminal=false
Type=Application
Categories=System;Utility;X-Fedora;
Keywords=clean;codec;fedora;fix;install;proprietary;

2) **yad icon browser**
#!/usr/bin/env xdg-open
[Desktop Entry]
Name=Icon Browser
Name[fr]=Navigateur d'Icônes
Name[it]=Navigatore di icone
Name[pt_BR]=Ícone do navegador
Name[ru]=Броузер иконок
Name[sk]=Prehliadač ikon
Name[uk]=Павігатор іконок
Name[zh_TW]=圖示瀏覽器
Comment=Inspect GTK Icon Theme
Comment[fr]=Parcourir les icônes du thème GTK
Comment[it]=Sfoglia le icone del tema GTK
Comment[pt_BR]=Inspecionar ícone tema do GTK
Comment[ru]=Исследование темы иконок GTK
Comment[sk]=Preskúmať tému ikon GTK
Comment[uk]=Перегляд теми іконок GTK
Comment[zh_TW]=檢閱 GTK 圖示布景主題
Categories=GTK;Utility;
Exec=yad-icon-browser
Icon=yad
Terminal=false
Type=Application
StartupNotify=true
X-Desktop-File-Install-Version=0.23

3) **exult**
#!/usr/bin/env xdg-open
[Desktop Entry]
Name=Exult
Comment=Exult Ultima 7 Engine
Exec=exult
Icon=exult
Terminal=false
Type=Application
Categories=Game;RolePlaying;

4) **menulibre**
#!/usr/bin/env xdg-open
[Desktop Entry]
Name=Menu Editor
Name[ca]=Editor dels menús
Name[cs]=Editor nabídky
Name[de]=Menübearbeitung
Name[el]=Επεξεργαστής Μενού
Name[en_AU]=Menu Editor
Name[en_GB]=Menu Editor
Name[es]=Editor de menús
Name[eu]=Menu-editorea
Name[fi]=Valikkomuokkain
Name[fr]=Éditeur de menus
Name[fy]=Menu bewurkje
Name[he]=עורך תפריט
Name[hr]=Uređivač izbornika
Name[is]=Valmyndaritill
Name[it]=Editor del Menu
Name[ja]=メニューエディター
Name[ko]=메뉴 편집기
Name[lt]=Meniu redaktorius
Name[ms]=Penyunting Menu
Name[nl]=Menu bewerken
Name[pl]=Edytor menu
Name[pt]=Editor de menu
Name[pt_BR]=Editor de Menus
Name[pt_PT]=Editor de Menus
Name[ru]=Редактор меню
Name[si]=මෙනු සංස්කාරකය
Name[sl]=Urejevalnik menijev
Name[sr]=Уређивач изборника
Name[sv]=Menyredigerare
Name[uk]=Редактор меню
Name[zh_CN]=菜单编辑器
Name[zh_TW]=選單編輯器
Comment=Add or remove applications from the menu
Comment[cs]=Přidat nebo odebrat programy z nabídky
Comment[de]=Anwendungen aus bzw. zu diesem Menü hinzufügen oder entfernen
Comment[el]=Προσθήκη ή αφαίρεση εφαρμογών από το μενού
Comment[en_GB]=Add or remove applications from the menu
Comment[es]=Añadir o eliminar aplicaciones del menú
Comment[eu]=Gehitu edo kendu menuko aplikazioak
Comment[fi]=Lisää tai poista sovelluksia valikosta
Comment[fr]=Ajouter ou retirer des applications du menu
Comment[he]=הוסף או הסר יישומים מתוך התפריט
Comment[hr]=Dodaj ili ukloni program iz izbornika
Comment[is]=Bættu við eða fjarlægðu forrit úr valmyndinni
Comment[it]=Aggiungi e rimuovi applicazioni dal menù
Comment[ja]=メニューにあるアプリケーションの追加と削除
Comment[lt]=Pridėkite ar šalinkite meniu programas
Comment[ms]=Tambah atau buang aplikasi dari menu
Comment[nl]=Toepassingen aan het menu toevoegen of daaruit verwijderen
Comment[pl]=Dodaje i usuwa programy z menu
Comment[pt]=Adicionar ou remover aplicações ao menu
Comment[pt_BR]=Adicione ou remove programas do menu
Comment[pt_PT]=Adicionar ou remover aplicações do menu
Comment[ru]=Добавление и удаление пунктов меню
Comment[sl]=Dodajte ali odstranite program iz menija
Comment[sr]=Додаје или уклања програме у изборнику
Comment[sv]=Lägg till eller ta bort program från menyn
Comment[uk]=Додавання або вилучення програм з меню
Comment[zh_CN]=从菜单中添加或移除应用程序
Comment[zh_TW]=在選單加入或移除應用程式
Exec=/usr/bin/menulibre
Terminal=false
Type=Application
StartupNotify=true
Categories=GNOME;Settings;DesktopSettings;Utility;
Keywords=Configuration;Menu;User;
Icon=menulibre
X-Ubuntu-Gettext-Domain=menulibre

5) **QT4 Config**
#!/usr/bin/env xdg-open
[Desktop Entry]
Name=Qt4 Config 
Comment=Configure Qt4 behavior, styles, fonts
Exec=qtconfig-qt4
Icon=qt4-logo
Terminal=false
Type=Application
Categories=Qt;Settings;
X-Desktop-File-Install-Version=0.22

6)**PostInstallerF**
[Desktop Entry]
Name=PostIntallerF
GenericName=postinstallerf
Comment=PostInstallerF will install all the software that Fedora doesn't include by default, after running Fedora for the first time
Icon=/usr/share/icons/Postinstaller1.svg
Type=Application
Categories=GTK;Utility;System;
Exec=/usr/bin/postinstallerf/principal-menu
StartupNotify=false

Thanks a lot for your time and your great work!

**Comment by rudrab** [comment]
Hi,
Thanks for your icon request. U am wokring on this. Can you kindly show me the fedy and yad's icon in your default icon pack? I am unable to find how the default icon looks like.

**Comment by Apopatos** [comment]
Hi,
here they are:
![icons](https://cloud.githubusercontent.com/assets/25205438/22112704/9ccfde4a-de6c-11e6-8a4e-e792e7af673b.png)
Yad is the bottle in last line, second road.

**Comment by rudrab** [comment]
Hi,
I have pushed the icons. Though I am not sure how good its going to work with Qt apps. Please try and comment.

**Comment by Apopatos** [comment]
They look great! Thanks a ton and please continue your great work!
Donated a few bucks.
![icons2](https://cloud.githubusercontent.com/assets/25205438/22129455/c43b7ca4-deae-11e6-80ec-05db3906d16b.png)
![icons3](https://cloud.githubusercontent.com/assets/25205438/22129456/c43e4f88-deae-11e6-9ef3-d9fdee1ff8c4.png)

**Comment by rudrab** [comment]
Thanks a lot for the coffee...that is really encouraging. 
One thing I realized after seeing your screenshot, that I have done `PostinstallerF` ,  it is not working because of its absolute path : `Icon=/usr/share/icons/Postinstaller1.svg`
Please convert it to `Icon=Postinstaller1`, and it should work.

**Comment by Apopatos** [comment]
Done! It works now!
Thank you!

**Comment by Apopatos** [comment]
One icon that it seems I forgot, is the **LASH Panel**. And the default icon looks really ugly!

[Desktop Entry]
Name=LASH Panel
GenericName=LASH Control Panel
Comment=LASH Control Panel
Icon=lash
Exec=lash_panel
Terminal=false
Type=Application
Categories=AudioVideo;X-Lash;X-Jack;X-AudioVideoTools;
X-Desktop-File-Install-Version=0.23

**Comment by rudrab** [comment]
done and pushed.

**Comment by rudrab** [comment]
One more thing...I just noticed the flash is not themed in your desktop. But flash is themed in the icon. if you can send me the ,desktop for flash, i can just link it.

**Comment by Apopatos** [comment]
Thank you, it looks great!


[Desktop Entry]
Name=Adobe Flash Player
Comment=Preferences for Adobe Flash Player
Comment[bg]=Настройки за Adobe Flash Player
Comment[ca]=Preferències quant a la Adobe Flash Player
Comment[de]=Einstellungen zur Adobe Flash Player
Comment[es]=Preferencias para Adobe Flash Player
Comment[fr]=Préférences pour Adobe Flash Player
Comment[gl]=Preferencias para Adobe Flash Player
Comment[nb]=Brukervalg for Adobe Flash Player
Comment[nl]=Voorkeuren voor Adobe Flash Player
Comment[pl]=Preferencje Adobe Flash Player
Comment[pt]=Preferências para a Adobe Flash Player
Comment[pt_BR]=Preferências para o Adobe Flash Player
Comment[ru]=Настройки для Adobe Flash Player
Comment[sk]=Predvoľby pre Adobe Flash Player
Comment[sv]=Inställningar för Adobe Flash Player
Exec=flash-player-properties
Icon=flash-player-properties
Terminal=false
Type=Application
StartupNotify=true
Categories=Settings;GNOME;GTK;X-GNOME-PersonalSettings;
NotShowIn=KDE;

I created a link with the name flash-player-properties and it works now ;-)
![icon4](https://cloud.githubusercontent.com/assets/25205438/22149991/590f1596-df1f-11e6-9cdc-95b5af31ab69.png)

**Comment by rudrab** [comment]
> I created a link with the name flash-player-properties and it works now ;-)
Thats great. I have also put it. so, a pull will also do. :)

**Comment by Apopatos** [comment]
;-)
