### ISSUE TITLE
Icon Request: LightWorks

### ISSUE THREAD

**Issue by Apopatos** [rudrab/Shadow#73]
Commercial video editor but very popular.
[Desktop Entry]
Version=12.6
Name=Lightworks
Comment=Cross-platform film & video editor
Exec=/usr/bin/lightworks
Icon=/usr/share/lightworks/Icons/App.png
Terminal=false
Type=Application
Categories=AudioVideo;AudioVideoEditing;
StartupWMClass=Ntcardvt
![lightworks](https://cloud.githubusercontent.com/assets/25205438/22249083/34ed3d7c-e24a-11e6-9e2c-4b9d74d0687e.png)

Also, would be possible to change the icon of **Deluge** in system tray? Right now it looks very dissimilar.
![deluge](https://cloud.githubusercontent.com/assets/25205438/22249179/8afb4114-e24a-11e6-9e11-bc166c507434.png)

Thank you!

**Comment by rudrab** [comment]
hi, a lightwork icon is included, https://github.com/rudrab/Shadow/blob/master/scalable/apps/lightworks.svg

It is not working because `Icon=/usr/share/lightworks/Icons/App.png` is an absolute path. without changing this, it is not possible to be themed.

You can put something like this:
```
[Desktop Entry]
Version=12.6
Name=Lightworks
Comment=Cross-platform film & video editor
Exec=/usr/bin/lightworks
Icon=lightworks
Terminal=false
Type=Application
Categories=AudioVideo;AudioVideoEditing;
StartupWMClass=Ntcardvt
```

to `~/.local/share/applications/lightworks.desktop` and it should work.

Thanks for `Deluge` comment. I will look at it.

**Comment by Apopatos** [comment]
Thank you. I hadn't notice!

**Comment by rudrab** [comment]
deluge pushed....kindly pull and check again.
Please, if you have gnome-look accont, dont forget to upvote.

**Comment by Apopatos** [comment]
Hi, Deluge still looks the same.

I've upvoted already ;-)

**Comment by rudrab** [comment]
> Hi, Deluge still looks the same.

thats odd...can you logout and login again?

**Comment by Apopatos** [comment]
I did. Nothing changed.

**Comment by rudrab** [comment]
thats really odd...is there any extension you are using?

**Comment by Apopatos** [comment]
I disabled every extension and logged out. Still the same :-(
![tray](https://cloud.githubusercontent.com/assets/25205438/22252546/3588ba4c-e257-11e6-94e0-f68aa2ade839.png)

**Comment by rudrab** [comment]
if you go to `.icons/shadow/scalable/apps`,  and `grep deluge`, what is the output?

**Comment by Apopatos** [comment]
![2017-01-24 17-11-51](https://cloud.githubusercontent.com/assets/25205438/22252865/41d09ae4-e258-11e6-9b47-a65aa80365b6.png)

**Comment by rudrab** [comment]
whom....that's really odd. Don't know why this is happening. I need to check

**Comment by rudrab** [comment]
Hi, can you tell me the extension u are using to put the icon at the top bar?

**Comment by rudrab** [comment]
![screenshot from 2017-01-24 17-32-11](https://cloud.githubusercontent.com/assets/4639447/22256623/a03bd29e-e25b-11e6-8e78-c6fe219ecaa3.png)
This is what I am getting, and it seems consistent. the Deluge icon on the topicon takes the normal X11 icons, not the symbolic one. Though, I will ask it in the #irc once i am back home.

**Comment by Apopatos** [comment]
Hi, I use this extension.
https://extensions.gnome.org/extension/1031/topicons/
