### ISSUE TITLE
Icon request (3 more)

### ISSUE THREAD

**Issue by murpholinox** [rudrab/Shadow#75]
Xournal++  https://github.com/xournalpp/xournalpp

[Desktop Entry]
Encoding=UTF-8
Type=Application

Name=Xournal++
Comment=Take handwritten notes
Name[fr]=Xournal++
Comment[fr]=Prise de notes manuscrites
Name[ca]=Xournal++
Comment[ca]=Preneu notes a mà
Name[de]=Xournal++
Comment[de]=Handnotizen erstellen
Name[pl]=Xournal++
Comment[pl]=Notatki odręczne

Exec=xournalpp %f
Terminal=false
StartupNotify=true
MimeType=application/x-xoj;application/pdf;
Icon=xournalpp
Categories=GNOME;GTK;Utility;TextEditor;

xds-viewer http://xds-viewer.sourceforge.net/

[Desktop Entry]
Encoding=UTF-8
Name=XDS-Viewer
Comment=XDS-Viewer
TryExec=xds-viewer
Exec=xds-viewer
Terminal=false
Type=Application
Categories=Graphics;Viewer;
Icon=/usr/share/xds-viewer/xds-viewer-50px.png
X-SuSE-translate=false

and
coot https://www2.mrc-lmb.cam.ac.uk/personal/pemsley/coot/
[Desktop Entry]
Type=Application
Encoding=UTF-8
Name=Coot
Comment=Macromolecular model builder
Exec=coot
Icon=coot.png
Terminal=true
Categories=Science;Graphics
MimeType=chemical/x-pdb;chemical/x-mmcif;chemical/x-mdl-molfile

**Comment by rudrab** [comment]
Hi,
Thanks for your request. 
But, as I can see, `xds-viewer` is using absolute path, so does not support themes trivially. you will need to edit that, 
I will update the icons soon.

**Comment by murpholinox** [comment]
So...How I do that? Do I have to change the Icon line in the .desktop file?  Which icon size do I choose?

Ps Not sure if this helps but i am in gnome

**Comment by rudrab** [comment]
Hi,
copy the .desktop file to `~/.local/share/applications` and change the Icon line as:

`Icon=xds-viewer`

This will do that.

NB: you can off course change it in `/usr/local/applications`; but copying it to your `$home` has the advantage that it won't be overwritten with updates.
