### ISSUE TITLE
Remarkable - misnamed

### ISSUE THREAD

**Issue by happydemic** [rudrab/Shadow#79]
There's a typo in the name of the pretty icon for Remarkable created in response to https://github.com/rudrab/Shadow/issues/77.

The .desktop looks for **remarkable** but the Shadow icon is named [**remerkable**](https://github.com/rudrab/Shadow/blob/master/scalable/apps/remerkable.svg).

**Comment by rudrab** [comment]
Thanks a lot for the report. updated.
