### ISSUE TITLE
Icon Request: Lollypop

### ISSUE THREAD

**Issue by terencode** [rudrab/Shadow#82]
Hi, thanks for this very cool icon theme, I was wondering if someone would make something like this :)

Desktop file is [here](https://drive.google.com/open?id=0B-u7ZMo7krOdWVRkUUxsazNldkU).

**Comment by rudrab** [comment]
Hi,
Lollypop was already themed, but I was not aware it is renamed to org.gnome.lollypop.
It is updated. please pull.

**Comment by terencode** [comment]
I did but icon does not get updated.

**Comment by rudrab** [comment]
It should work now.

**Comment by terencode** [comment]
It's working now, thank you for your reactivity!
