### ISSUE TITLE
Icon request & color request

### ISSUE THREAD

**Issue by juhaku** [rudrab/Shadow#83]
Hello, how about making icon for Visual Studio Code application. https://code.visualstudio.com/

And it would be great if there would be orange version of places available as well.

**Comment by rudrab** [comment]
hi, visualstudio is already themed.
Please send me the corresponding desktop file, so that I can update it.
Also, thanks for your suggestion of orange theme. I will try to update it soon.

**Comment by juhaku** [comment]
Following zip file contains the abovementioned visual studio code desktop file zipped.

[code.zip](https://github.com/rudrab/Shadow/files/991034/code.zip)

**Comment by rudrab** [comment]
pushed.
Please pull it from github

**Comment by rudrab** [comment]
Hi, orange version of places added (garnet).

**Comment by gauthiermartin** [comment]
Would it be possible to change color to the blue color used into visual code logo ?

[https://image.apphit.com/image/visual-studio-code/visual-studio-code-logo.png](url)

**Comment by rudrab** [comment]
oops...sure! my mistake.
