### ISSUE TITLE
changecolor.py: error on option 4 (Torquiose)

### ISSUE THREAD

**Issue by ThanosApostolou** [rudrab/Shadow#84]
I created a package for fedora, which I included in a copr repository (https://copr.fedorainfracloud.org/coprs/thanosapostolou/icon-themes/package/shadow-icon-theme/). However, I cannot generate the Torquiose colours with the **changecolor.py**. I'm using the latest snapshot. The error is this:
```
1:  Emerald  
2:   Ruby    
3: Sapphire  
4: Torquiose 
9:Square
Choose one of the color scheme:4
TORQUISE scheme will be applied
places_torquise
./places_torquise/system-file-manager.svg
Traceback (most recent call last):
  File "./changecolor.py", line 34, in <module>
    shutil.copy(nautilaus,"./apps")
  File "/usr/lib64/python2.7/shutil.py", line 119, in copy
    copyfile(src, dst)
  File "/usr/lib64/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: './places_torquise/system-file-manager.svg'
```

**Comment by rudrab** [comment]
Hi,
Thanks a lot for creating the copr. I tried that once and failed. 
I have added the `places_torquise/system-file-manager.svg` (no idea how I lost it).
Kindly try it once again.

**Comment by ThanosApostolou** [comment]
@rudrab Same error on the with the latest snapshot. I think there is a typo because it says:
```
No such file or directory: './places_torquise/system-file-manager.svg'
```

The **changecolor.py** searches for:
```
scheme = "torquise"
```
I believe that this should be **torquiose** instead.

Also in the commit I see the file:
```
scalable/places_turquoise/system-file-manager.svg
```
I believe this should be **places_torquiose**

**Comment by rudrab** [comment]
Thanks a lot.
It is corrected now. Also, I have added a new color scheme. Kindly check.

Also, as you have created the copr, should I tag you as I update the theme? or it will be automatically updated using git?

**Comment by ThanosApostolou** [comment]
Nice, works perfectly now!

I don't think that copr has any mechanism to automatically update packages using git (I only recently started using Fedora and learning its infrastructure, so there may be such a thing which I haven't learned yet).

So, feel free to tag me, or if you don't I will manually check for updates every few weeks.

I'm also trying to become an official packager for Fedora, so if I succeed, I might manage to get the Theme into the official repositories in the future.

Here's the spec file: http://copr-dist-git.fedorainfracloud.org/cgit/thanosapostolou/icon-themes/shadow-icon-theme.git/tree/shadow-icon-theme.spec, in case you want to improve it or create your own separate copr repository (because I have made a general **icon-themes** repository in which I intend to include several icon themes in the future). I don't like the way I choose the colour schemes with the echo commands:
`echo 3| ./changecolor.py` 
If there's a better way to do that please tell me (my bash skills aren't greate 😛 ).

The new colour looks nice btw:
![screenshot at 2017-05-21 13-39-50](https://cloud.githubusercontent.com/assets/21288843/26283211/fd6b7736-3e2b-11e7-9b94-dad0bbc3d8b3.png)

Keep up the good work mate!!
