### ISSUE TITLE
Icon Request : IntelliJ IDEA 

### ISSUE THREAD

**Issue by gauthiermartin** [rudrab/Shadow#87]
It would be nice to have an intelli j idea j icon

**Comment by rudrab** [comment]
hi, 
Thanks for your request.
kindly add the corresponding .desktop file.

**Comment by gauthiermartin** [comment]
Here it is 
[mysql-workbench.desktop.zip](https://github.com/rudrab/Shadow/files/1129170/mysql-workbench.desktop.zip)

**Comment by gauthiermartin** [comment]
Here it is 
[jetbrains-idea.desktop.zip](https://github.com/rudrab/Shadow/files/1129173/jetbrains-idea.desktop.zip)

**Comment by rudrab** [comment]
hi,
intellij IDEA is already themed.  It does not work because the absolute path used in .desktop file:
`Icon=/opt/idea/bin/idea.png
`
For this to work, kindly use this .desktop file in ~/.local/share/application
**jetbrains-idea.desktop**
```
#!/usr/bin/env xdg-open
[Desktop Entry]
Version=1.0
Type=Application
Name=IntelliJ IDEA
Icon=IntelliJ
Exec="/opt/idea/bin/idea.sh" %f
Comment=The Drive to Develop
Categories=Development;IDE;
Terminal=false
StartupWMClass=jetbrains-idea

```

**Comment by gauthiermartin** [comment]
Alright, Sorry for that ! Thank you

**Comment by rudrab** [comment]
You are welcome.
Kindly let me know if this is working.

**Comment by gauthiermartin** [comment]
Yeah this is working perfectly ; -)
