### ISSUE TITLE
Icon Request : MySQL Workbench

### ISSUE THREAD

**Issue by gauthiermartin** [rudrab/Shadow#88]
It would be nice to have an MySQL Workbench Icon

**Comment by rudrab** [comment]
Please check the comment on #87

**Comment by gauthiermartin** [comment]
Here it is 
[mysql-workbench.desktop.zip](https://github.com/rudrab/Shadow/files/1129174/mysql-workbench.desktop.zip)

**Comment by gauthiermartin** [comment]
[Desktop Entry]
Name=MySQL Workbench
Comment=MySQL Database Design, Administration and Development Tool
Exec=mysql-workbench %f
Terminal=false
Type=Application
Icon=mysql-workbench
MimeType=application/vnd.mysql-workbench-model;application/sql;
Categories=GTK;Database;Development;
StartupWMClass=mysql-workbench-bin
