### ISSUE TITLE
New Icon Request

### ISSUE THREAD

**Issue by maxnumberone** [rudrab/Shadow#9]
Hello,
Thanks for the previous one, that was fast.
Here are a new set of missing icons (icon name is the same as the icon map if not specified) :

gconf-editor : edit the entire configuration database
gksu-properties (icon name gksu) : Configure behavior of the privilege-granting tool
gnome-mplayer
gnome-subtitles : subtitle editor
gtranslator : enhanced gettext po file editor
keepass/keepassx2 there is already an icon named keepassx, maybe you could link to the 2 others as I don't believe people will install more than one at a time.
meld : Compare and merge files
pdfshuffler : simple modifications GUI for pdf documents
pinta : drawing and image editing
qv4l2 : Allow testing Video4Linux devices
spotify (icon name: spotify-client) spotify icon already exists, could you please add a link ?
subdownloader : GUI for downloading/uploading subtitles
sweethome3d : interior design application
transmageddon : video transcoder
wireshark
zenmap : GUI for Nmap

I also have these QT based apps without shadowed icon (only assistant-qt4 icon exists) :
designer-qt4 : Design GUIs for Qt4 applications
linguist-qt4 : Add translations to Qt4 applications
qdbusviewer-qt4 : Debug D-Bus applications

these should be the last ones missing for me ;)

Thank you
Regards

**Comment by rudrab** [comment]
Thanks for your list. I will upload that ASAP. 

But just for query, gconf? If you don't mind, may I know the distro you are using? It is long being replaced by dconf, isn't it?

**Comment by maxnumberone** [comment]
You're right but I still have some apps parameter's stored in gconf-editor.
I'm using ArchLinux, but maybe it is more related to the apps I use.
I wasn't really aware of this ;)

**Comment by rudrab** [comment]
Hi, 
Thanks for the iconlists. Icons are added. Please pull it again.

**Comment by rudrab** [comment]
I am closing this issue now. But feel free to reopen and comment

**Comment by maxnumberone** [comment]
Thanks, nearly everything is present.
But I think you have forgotten pinta and pdf-shuffler ;)

**Comment by rudrab** [comment]
Oops...I am so sorry.
Now they are updated. Kindly check again.

**Comment by maxnumberone** [comment]
No problem, you're making an amazing job on this theme, it's very nice.
Thanks
