### ISSUE TITLE
Icon Request: MPLABX (IDE and IPE) and kicad

### ISSUE THREAD

**Issue by palua** [rudrab/Shadow#91]

**Comment by rudrab** [comment]
Thanks for your request. 
Kindly give me the .desktop file, and if possible, the default icon. That will help me speed up the process.

**Comment by palua** [comment]
Hi,

here the .desktop file of both applications:

[Desktop Entry]
Name=MPLAB IDE
Comment=IDE for Microchip PIC and dsPIC development
Exec=/usr/bin/mplab_ide
Icon=mplab_ide.png
Terminal=false
Type=Application
Categories=Application;Development;Programming;
StartupNotify=true

[Desktop Entry]
Name=MPLAB IPE
Comment=IPE for Microchip PIC and dsPIC programming
Exec=/usr/bin/mplab_ipe
Icon=mplab_ipe.png
Terminal=false
Type=Application
Categories=Application;Development;Programming;
StartupNotify=true

in attachment the default icons of the MPLABX application.

kicad's .desktop file:

[Desktop Entry]
Categories=Development;Electronics;
Comment=Design a printed circuit board
Exec=kicad %f
Keywords=Kicad;Projectmanager;
GenericName=EDA Suite
Icon=applications-electronics
MimeType=application/x-kicad-project;
Name=KiCad
Type=Application

in attachment the default icon of kicad as well.


I take this opportunity to congratulate with you for the great theme you 
have created, really a good job with a lot of excellent icons, also for 
very particular applications.

**Comment by rudrab** [comment]
Hi, Thanks a lot for your reply. Unfortunately, I haven't found the attachments. I will try to get them from web, but it will be really helpful if you can send them to me some way (dropbox/google drive etc may be?)

**Comment by palua** [comment]
I have resent the attachments, tell me if this time you can download them.
If not tell me how I can send them with dropbox (I have a dropbox account)

2017-07-24 11:52 GMT+02:00 rudrab <notifications@github.com>:

**Comment by rudrab** [comment]
Sorry, but I am confused. I can't see any attachment here.

**Comment by palua** [comment]
I have uploaded the icons on my dropbox. this is the link:

https://www.dropbox.com/sh/twn0903x0b4jz2y/AAD55lEvTXGgTUXI95dUV262a?dl=0


I hope this will work

**Comment by rudrab** [comment]
Hi, Thanks a lot. Its working. I will upload it ASAP.
