### ISSUE TITLE
Icon Request: vmware player & nvidia setting

### ISSUE THREAD

**Issue by gionno** [rudrab/Shadow#92]
here the desktop

vmware player

[Desktop Entry]
Encoding=UTF-8
Name=VMware Player
Comment=Run a virtual machine
Exec=/usr/bin/vmplayer %u
Terminal=false
Type=Application
Icon=vmware-player
StartupNotify=true
Categories=System;
MimeType=application/x-vmware-vm;application/x-vmware-enc-vm;x-scheme-handler/vmrc;

Nvidia

[Desktop Entry]
Type=Application
Encoding=UTF-8
Name=NVIDIA X Server Settings
Comment=Configure NVIDIA X Server Settings
Exec=/usr/bin/nvidia-settings
Icon=/usr/share/pixmaps/nvidia-settings.png
Categories=Application;Settings;

plus: a problem with vlc:
if the application is open the icon change to:

![icon](http://i63.tinypic.com/24fmcnt.png)

it's a setting of my desktop or is non supported?

**Comment by rudrab** [comment]
Hi, 
Thanks for your request. 
I will add vmware-player as soon as possible.
Nvidia is already themed. check my reply on #77  for more.
vmc problem is a generic problem that qt-based apps do not support transparency. 
I will do a seperate repo for them soon.
