### ISSUE TITLE
All folder icons switched to text file icon

### ISSUE THREAD

**Issue by sanguine8082** [rudrab/Shadow#93]
![image](https://user-images.githubusercontent.com/8801258/29049551-3ff51a28-7b9c-11e7-91af-9ebc680b4ec4.png)

Not sure what happened, just ran through an update very recently and this was the result.  Not sure if I need to reconfigure or what.

**Comment by rudrab** [comment]
Hi, this is odd. Are you getting expected icons with default theme? 
Kindly give me the output of 
file desktop 
And also, which version of shadow are you using?

**Comment by sanguine8082** [comment]
This is what it looks like:

![image](https://user-images.githubusercontent.com/8801258/29300877-048dd3ce-813e-11e7-8dcc-63385c290428.png)

How do I check which version I'm using?

**Comment by sanguine8082** [comment]
Switching back to the default system icons works, but I like the shadow icons!

**Comment by rudrab** [comment]
Hi, its my pleasure that you like the shadow icon. 
I am just try to figure out what made this problem.
have you run the changecolour.py code ?

**Comment by sanguine8082** [comment]
I'm not even sure what that python script is.  Where could I find it?

**Comment by rudrab** [comment]
Hi, if you have some time, can we try to solve it step by step?
first, please do this:
```
$cd .icons/shadow
$ tree -L 1
```

and please paste the output. 
Also, inside `.icons/shadow`, you have the `changecolour.py` code. Run it using:
`$python3 ./changecolour.py` and choose among any color of your choice. Kindly let me know if this works.

**Comment by rudrab** [comment]
hi,
I have pushed  a new version both here in github and in gnome-look. Kindly check if that solves your problem.

**Comment by sanguine8082** [comment]
I'm sorry I never got back to you on running those troubleshooting steps above.  I've been super busy, and haven't even pulled my laptop out in like a week 😢 

I will try and check out that new version here in the next day or so.  Thank you so much man!

**Comment by rudrab** [comment]
hi, can you kindly tell me the status?

**Comment by sanguine8082** [comment]
I actually switched desktop environments and never got a chance to try this
out :(

**Comment by rudrab** [comment]
ok. BTW, now you can use gnome, unity, pantheon and mate in this icon. 
Anyway, I am closing this issue now.
