### ISSUE TITLE
Icon Request: Scrivener

### ISSUE THREAD

**Issue by happydemic** [rudrab/Shadow#96]
Thanks so much for doing so many new icons on request. If you have time and inclination: 

**Scrivener** writing software - now abandonware on Linux, but still widely used.
Scrivener.desktop
`Icon=Scrivener`
![scrivener](https://user-images.githubusercontent.com/12738878/29484384-74bb5ae8-84b5-11e7-89f5-35d81bb9dbab.png)

**Comment by happydemic** [comment]
Stylish... thank you! Now I have no excuse for procrastination. ;)

**Comment by rudrab** [comment]
Glad that you liked it. 
Thanks
