### ISSUE TITLE
Icon request: Rocketchat and Adobe Photoshop

### ISSUE THREAD

**Issue by Mildpaul** [rudrab/Shadow#97]
Super awesome icon set, love it! But I am missing icons for Rocketchat and Photoshop which I use daily.

**Comment by rudrab** [comment]
Glad that you like the icon set. I will be more than happy to make those icons missing. Can you give me the corresponding .desktop files and the icons, if possible?

**Comment by rudrab** [comment]
Hi, the icons are done...I am just waiting for you to let me know the icon name of adobe-photoshop icon.

**Comment by Mildpaul** [comment]
Oh wow, that was quick! I had already left for the night :)

I'd guess the icon name for Photoshop would be "adobe-photoshop" and "AdobePhotoshop" judging from how the other adobe app icons are named in many icon sets.

I run it using Wine since it is one of those apps that doesn't have a native Linux version, so I'll have to set the icon on the shortcut manually.

**Comment by Mildpaul** [comment]
Thanks Rudrab, the new icons look awesome, and now my desktop is beautiful

**Comment by rudrab** [comment]
Thanks for letting me know. If you have some time, please upvote in gnome-look

**Comment by Mildpaul** [comment]
Already upvoted :)
