### ISSUE TITLE
icon request

### ISSUE THREAD

**Issue by delta1071** [rudrab/Shadow#98]
Have just discovered shadow icons and I love the look! I'd like to request icons for Thunar File Manager and QMMP (the Winamp-inspired music player). Thanks for all your hard work in creating and maintaining this icon pack.

Regards,

Steve Silvi

**Comment by rudrab** [comment]
Hi,
Glad that you like it. Thunar is already themed, but may be they have changed the name. Can you kindly send me the corresponding .desktop file for both files?

**Comment by rudrab** [comment]
You may find how to do that here:
https://rudrab.github.io/Shadow/#new-icon-request

**Comment by delta1071** [comment]
I hope the attached files are what you are asking for.

**Comment by rudrab** [comment]
Hi, unfortunately, I cant see any files attached. 
I have done qmmp, and the thunar's name is matching the fedora installation. So, I just need your thunar's icon name (in thunar.desktop)

**Comment by delta1071** [comment]
Not sure which filename you need, so am attaching text file with 
contents of thunar.desktop. BTW, I'm using Thunar in Ubuntu MATE-17.04 
if it makes a difference.

On Fri, Aug 25, 2017 at 8:17 AM, rudrab <notifications@github.com> 
wrote:
> Hi, unfortunately, I cant see any files attached.
> I have done qmmp, and the thunar's name is matching the fedora 
> installation. So, I just need your thunar's icon name (in 
> thunar.desktop)
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

[Desktop Entry]
Name=Thunar File Manager
Name[ar]=مدير الملفات ثونار
Name[ast]=Xestor de ficheros Thunar
Name[be]=Кіраўнік файлаў Thunar
Name[bg]=Файлов мениджър Thunar
Name[bn]=Thunar ফাইল ম্যানেজার
Name[ca]=Gestor de fitxers Thunar
Name[cs]=Správce souborů Thunar
Name[da]=Thunar-filhåndtering
Name[de]=Thunar-Dateiverwaltung
Name[el]=Διαχειριστής αρχείων Thunar
Name[en_AU]=Thunar File Manager
Name[en_GB]=Thunar File Manager
Name[eo]=Thunar dosier-administrilo
Name[es]=Gestor de archivos Thunar
Name[et]=Failihaldur Thunar
Name[eu]=Thunar fitxategi kudeatzailea
Name[fa_IR]=مدیر پرونده‌های تونار
Name[fi]=Thunar-tiedostonhallinta
Name[fr]=Gestionnaire de fichiers Thunar
Name[gl]=Xestor de ficheiros Thunar
Name[he]=מנהל קבצים Thunar
Name[hr]=Thunar upravitelj datotekama
Name[hu]=Thunar fájlkezelő
Name[id]=Manajer Berkas Thunar
Name[is]=Thunar skráastjóri
Name[it]=Il gestore di file Thunar
Name[ja]=Thunar ファイルマネージャー
Name[kk]=Thunar файлдар басқарушысы
Name[ko]=투나 파일 관리자
Name[lt]=Thunar failų tvarkytuvė
Name[lv]=Thunar failu pārvaldnieks
Name[ms]=Pengurus Fail Thunar
Name[nb]=Thunar Filbehandler
Name[nl]=Thunar bestandbeheerder
Name[nn]=Thunar filhandsaming
Name[oc]=Gestionari de Fichièrs Thunar
Name[pa]=ਥੰਨਰ ਫਾਇਲ ਮੈਨੇਜਰ
Name[pl]=Menedżer plików Thunar
Name[pt]=Gestor de ficheiros Thunar
Name[pt_BR]=Gerenciador de arquivos Thunar
Name[ro]=Managerul de fișiere Thunar
Name[ru]=Файловый менеджер Thunar
Name[si]=Thunar ගොනු කළමණාකරු
Name[sk]=Správca súborov Thunar
Name[sq]=Përgjegjësi i Kartelave Thunar
Name[sr]=Тунар управник датотека
Name[sv]=Filhanteraren Thunar
Name[te]=తునార్ దస్త్ర నిర్వాహకము
Name[th]=โปรแกรมจัดการแฟ้ม Thunar
Name[tr]=Thunar Dosya Yöneticisi
Name[ug]=سۇنار(Thunar) ھۆججەت باشقۇرغۇ
Name[uk]=Файловий менеджер Thunar
Name[ur]=تھنر فائل منیجر
Name[ur_PK]=تھنر فائل منیجر
Name[vi]=Trình quản lý tập tin Thunar
Name[zh_CN]=Thunar 文件管理器
Name[zh_HK]=Thunar 檔案管理員
Name[zh_TW]=Thunar 檔案管理員
Comment=Browse the filesystem with the file manager
Comment[ar]=تصفح ملفات النظام بمدير الملفات
Comment[ast]=Restolar el sistema de ficheros col xestor de ficheros
Comment[be]=Вандроўка па файлавай сыстэме з кіраўніком файлаў
Comment[bg]=Преглед на файловата система с файловият мениджър
Comment[bn]=ফাইল ম্যানেজার দিয়ে ফাইলসিস্টেম ব্রাউজ করুন
Comment[ca]=Navegueu pel sistema de fitxers amb el gestor de fitxers
Comment[cs]=Procházet systém souborů správcem souborů
Comment[da]=Gennemsøg filsystem med filhåndteringen
Comment[de]=Das Dateisystem in der Dateiverwaltung anzeigen
Comment[el]=Περιήγηση του συστήματος αρχείων με τον διαχειριστή αρχείων
Comment[en_AU]=Browse the filesystem with the file manager
Comment[en_GB]=Browse the filesystem with the file manager
Comment[eo]=Rigardu dosier-sistemon per dosier-administrilo
Comment[es]=Explore el sistema de archivos con el gestor de archivos
Comment[et]=Failisüsteemi lehitsemine kasutades failihaldurit
Comment[eu]=Fitxategi kudeatzaileaz fitxategi sistema arakatu
Comment[fi]=Selaa tiedostojärjestelmää tiedostonhallinnassa
Comment[fr]=Parcourir le système de fichiers avec le gestionnaire de fichiers
Comment[gl]=Explorar o sistema de ficheiros co xestor de ficheiros
Comment[he]=סייר במערכת הקבצים בעזרת מנהל הקבצים
Comment[hr]=Pregledaj datotečni sustav sa upraviteljem datoteka
Comment[hu]=A fájlrendszer böngészése a fájlkezelővel
Comment[id]=Ramban sistem berkas dengan manajer berkas
Comment[is]=Vafra um skráarkerfið með skráarstjóranum
Comment[it]=Esplora il file system con il gestore di file
Comment[ja]=ファイルマネージャーでファイルシステムを参照します
Comment[kk]=Файлдық жүйені файлдар басқарушысымен шолу
Comment[ko]=파일 관리자로 파일 시스템을 탐색합니다
Comment[lt]=Naršyti failų sistemą su failų tvarkytuve
Comment[lv]=Pārlūko failu sistēmu ar failu pārvaldnieku
Comment[ms]=Layar sistem fail dengan pengurus fail
Comment[nb]=Utforsk filsystemet med filbehandleren
Comment[nl]=Blader met de bestandbeheerder door het bestandssysteem
Comment[nn]=Bla gjennom filsystemet med filhandsamaren
Comment[oc]=Percórrer lo sistèma de fichièrs amb lo gestionari de fichièrs
Comment[pa]=ਫਾਇਲ ਮੈਨੇਜਰ ਨਾਲ ਫਾਇਲ ਸਿਸਟਮ ਨਾਲ ਬਰਾਊਜ਼ ਕਰੋ
Comment[pl]=Przegląda system plików za pomocą menedżera plików
Comment[pt]=Explorar sistema de ficheiros com o gestor de ficheiros
Comment[pt_BR]=Navegue no sistema de arquivos com o gerenciador de arquivos
Comment[ro]=Gestionați fișierele cu un manager dedicat
Comment[ru]=Просмотр файловой системы с помощью файлового менеджера
Comment[sk]=Prehliada súborový systém pomocou správcu súborov
Comment[sq]=Shfletoni sistemin e kartelave me përgjegjësin e kartelave
Comment[sr]=Прегледај систем датотека управником датотека 
Comment[sv]=Bläddra i filsystemet med filhanteraren
Comment[te]=దస్త్ర వ్యవస్థని దస్త్ర నిర్వాహకముతో విహరించు
Comment[th]=ท่องดูระบบแฟ้มด้วยโปรแกรมจัดการแฟ้ม
Comment[tr]=Dosya yöneticisi ile gezin
Comment[ug]=ھۆججەت باشقۇرغۇدا ھۆججەت سىستېمىسىنى كۆر
Comment[uk]=Перегляд файлової системи менеджером файлів
Comment[ur]=فائل سسٹم کو فائل منیجر سے دیکھیں
Comment[ur_PK]=فائل سسٹم کو فائل منیجر سے دیکھیں
Comment[vi]=Duyệt hê thống tập tin với trình quản lý tập tin
Comment[zh_CN]=用文件管理器浏览文件系统
Comment[zh_HK]=以檔案管理員瀏覽檔案系統
Comment[zh_TW]=使用檔案管理員瀏覽檔案系統
GenericName=File Manager
GenericName[am]=የ ፋይል አስተዳዳሪ
GenericName[ar]=مدير الملفات
GenericName[ast]=Xestor de ficheros
GenericName[be]=Кіраўнік файлаў
GenericName[bg]=Файлов мениджър
GenericName[bn]=ফাইল ব্যবস্থাপক
GenericName[ca]=Gestor de fitxers
GenericName[cs]=Správce souborů
GenericName[da]=Filhåndtering
GenericName[de]=Dateiverwaltung
GenericName[el]=Διαχειριστής αρχείων
GenericName[en_AU]=File Manager
GenericName[en_GB]=File Manager
GenericName[eo]=Dosier-administrilo
GenericName[es]=Administrador de archivos
GenericName[et]=Failihaldur
GenericName[eu]=Fitxategi kudeatzailea
GenericName[fa_IR]=مدیر پرونده
GenericName[fi]=Tiedostonhallinta
GenericName[fr]=Gestionnaire de fichiers
GenericName[gl]=Xestor de ficheiros
GenericName[he]=מנהל קבצים
GenericName[hr]=Upravitelj datotekama
GenericName[hu]=Fájlkezelő
GenericName[id]=Manajer Berkas
GenericName[is]=Skráastjóri
GenericName[it]=Gestore di file
GenericName[ja]=ファイルマネージャー
GenericName[kk]=Файлдар басқарушысы
GenericName[ko]=파일 관리자
GenericName[lt]=Failų tvarkytuvė
GenericName[lv]=Failu pārvaldnieks
GenericName[ms]=Pengurus Fail
GenericName[nb]=Filbehandler
GenericName[nl]=Bestandbeheerder
GenericName[nn]=Filhandsamar
GenericName[oc]=Gestionari de fichièrs
GenericName[pa]=ਫਾਇਲ ਮੈਨੇਜਰ
GenericName[pl]=Menedżer plików
GenericName[pt]=Gestor de ficheiros
GenericName[pt_BR]=Gerenciador de arquivos
GenericName[ro]=Manager de fișiere
GenericName[ru]=Файловый менеджер
GenericName[sk]=Správca súborov
GenericName[sq]=Përgjegjës Kartelash 
GenericName[sr]=Разгледач датотека
GenericName[sv]=Filhanterare
GenericName[te]=దస్త్ర నిర్వాహకము
GenericName[th]=โปรแกรมจัดการแฟ้ม
GenericName[tr]=Dosya Yöneticisi
GenericName[ug]=ھۆججەت باشقۇرغۇ
GenericName[uk]=Файловий менеджер
GenericName[ur]=فائل منیجر
GenericName[ur_PK]=فائل منیجر
GenericName[vi]=Trình quản lí tập tin
GenericName[zh_CN]=文件管理器
GenericName[zh_HK]=檔案管理員
GenericName[zh_TW]=檔案管理員
Exec=thunar %F
Icon=Thunar
Terminal=false
StartupNotify=true
Type=Application
Categories=System;Utility;Core;GTK;FileTools;FileManager;

# vi:set encoding=UTF-8:

**Comment by rudrab** [comment]
Hi,
Thanks. Its done. Please pull it from github (i.e. not gnome-looks repo).
Also, if you like the icons, please conside upvoting it in gnome-looks.

**Comment by delta1071** [comment]
Thanks for the speedy responses. I would have been glad to upvote even 
without these two icons added. They are great-looking icons and cover 
just about every app an everyday user would need.
